Repository OCA/timesheet, pull requests merged in 2019-02, with the labels that each got.

#153 [12.0][MIG] hr_timesheet_task_required
  hr_timesheet_task_required/README.rst
  hr_timesheet_task_required/__init__.py
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/i18n/fr.po
  hr_timesheet_task_required/i18n/hr_timesheet_task_required.pot
  hr_timesheet_task_required/models/__init__.py
  hr_timesheet_task_required/models/account_analytic_line.py
  hr_timesheet_task_required/models/project_project.py
  hr_timesheet_task_required/models/res_company.py
  hr_timesheet_task_required/models/res_config_settings.py
  hr_timesheet_task_required/readme/CONTRIBUTORS.rst
  hr_timesheet_task_required/readme/DESCRIPTION.rst
  hr_timesheet_task_required/static/description/icon.png
  hr_timesheet_task_required/static/description/index.html
  hr_timesheet_task_required/tests/__init__.py
  hr_timesheet_task_required/tests/test_hr_timesheet_task_required.py
  hr_timesheet_task_required/views/account_analytic_line.xml
  hr_timesheet_task_required/views/project_project.xml
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: approved, needs review, ready to merge

#182 [12.0][FIX] timesheet sheet lines inconsistency
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
Labels: approved

#181 [12.0][FIX] hr_timesheet_task_required: do not require task by default
  hr_timesheet_task_required/README.rst
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/models/project_project.py
  hr_timesheet_task_required/models/res_company.py
  hr_timesheet_task_required/readme/CONFIGURE.rst
  hr_timesheet_task_required/static/description/index.html
  hr_timesheet_task_required/tests/test_hr_timesheet_task_required.py
  hr_timesheet_task_required/views/project_project.xml
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: approved

#165 [12.0][ADD] hr_utilization_report: generate Utilization Report from Task Logs
  hr_utilization_report/README.rst
  hr_utilization_report/__init__.py
  hr_utilization_report/__manifest__.py
  hr_utilization_report/readme/CONTRIBUTORS.rst
  hr_utilization_report/readme/DESCRIPTION.rst
  hr_utilization_report/readme/ROADMAP.rst
  hr_utilization_report/readme/USAGE.rst
  hr_utilization_report/report/__init__.py
  hr_utilization_report/report/hr_utilization_report.py
  hr_utilization_report/report/hr_utilization_report.xml
  hr_utilization_report/static/description/index.html
  hr_utilization_report/tests/__init__.py
  hr_utilization_report/tests/test_hr_utilization_report.py
  hr_utilization_report/views/hr_department.xml
  hr_utilization_report/views/hr_employee.xml
  hr_utilization_report/wizards/__init__.py
  hr_utilization_report/wizards/hr_utilization_report_wizard.py
  hr_utilization_report/wizards/hr_utilization_report_wizard.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#167 [12.0][ADD] hr_utilization_analysis: review utilization in graph and pivot
  hr_utilization_analysis/README.rst
  hr_utilization_analysis/__init__.py
  hr_utilization_analysis/__manifest__.py
  hr_utilization_analysis/readme/CONTRIBUTORS.rst
  hr_utilization_analysis/readme/DESCRIPTION.rst
  hr_utilization_analysis/readme/USAGE.rst
  hr_utilization_analysis/report/__init__.py
  hr_utilization_analysis/report/hr_utilization_analysis.py
  hr_utilization_analysis/report/hr_utilization_analysis.xml
  hr_utilization_analysis/static/description/index.html
  hr_utilization_analysis/tests/__init__.py
  hr_utilization_analysis/tests/test_hr_utilization_analysis.py
  hr_utilization_analysis/views/hr_department.xml
  hr_utilization_analysis/views/hr_employee.xml
  hr_utilization_analysis/wizards/__init__.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.xml
Labels: approved, ready to merge

#184 [12.0][FIX] hr_timesheet_sheet: unlink only generated AAL
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved

#186 [12.0][FIX] hr_timesheet_task_required: warning on hr_timesheet_task_required
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/models/account_analytic_line.py
Labels: approved

#169 [ADD] HR Timesheet sheet attendance
  hr_timesheet_sheet_attendance/README.rst
  hr_timesheet_sheet_attendance/__init__.py
  hr_timesheet_sheet_attendance/__manifest__.py
  hr_timesheet_sheet_attendance/models/__init__.py
  hr_timesheet_sheet_attendance/models/hr_attendance.py
  hr_timesheet_sheet_attendance/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_attendance/readme/DESCRIPTION.rst
  hr_timesheet_sheet_attendance/readme/INSTALL.rst
  hr_timesheet_sheet_attendance/readme/USAGE.rst
  hr_timesheet_sheet_attendance/static/description/icon.png
  hr_timesheet_sheet_attendance/static/description/index.html
  hr_timesheet_sheet_attendance/tests/__init__.py
  hr_timesheet_sheet_attendance/tests/hr_timesheet_sheet_test_cases.py
  hr_timesheet_sheet_attendance/tests/test_hr_attendance.py
  hr_timesheet_sheet_attendance/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/views/hr_attendance_view.xml
  hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
Labels: approved, ready to merge

#192 [11.0][FIX] hr_timesheet_sheet: fix sheet_id calculation
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
Labels: approved

#193 [12.0][FIX] hr_timesheet_sheet: sheet_id when modifying the timesheet
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
Labels: approved

#194 [12.0][IMP] hr_timesheet_sheet: protect specific list of fields
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
Labels: approved

#195 [11.0][IMP] hr_timesheet_sheet: protect specific list of fields
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
Labels: approved
