Repository OCA/timesheet, pull requests merged in 2019-03, with the labels that each got.

#196 [11.0][IMP/FIX] hr_timesheet_sheet (partial)
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved

#158 [12.0][ADD] hr_timesheet_employee_required: require employee for Time Log
  hr_timesheet_employee_required/README.rst
  hr_timesheet_employee_required/__init__.py
  hr_timesheet_employee_required/__manifest__.py
  hr_timesheet_employee_required/models/__init__.py
  hr_timesheet_employee_required/models/account_analytic_line.py
  hr_timesheet_employee_required/readme/CONTRIBUTORS.rst
  hr_timesheet_employee_required/readme/DESCRIPTION.rst
  hr_timesheet_employee_required/static/description/index.html
  hr_timesheet_employee_required/tests/__init__.py
  hr_timesheet_employee_required/tests/test_hr_timesheet_employee_required.py
Labels: approved, ready to merge

#200 [12.0][IMP/FIX] hr_timesheet_sheet: port #196
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved

#119 [10.0][MIG] hr_timesheet_sheet_restrict_analytic
  hr_timesheet_sheet_restrict_project/README.rst
  hr_timesheet_sheet_restrict_project/__init__.py
  hr_timesheet_sheet_restrict_project/__manifest__.py
  hr_timesheet_sheet_restrict_project/models/__init__.py
  hr_timesheet_sheet_restrict_project/models/account_analytic_line.py
  hr_timesheet_sheet_restrict_project/static/description/icon.png
  hr_timesheet_sheet_restrict_project/static/src/js/restrict_timesheet.js
  hr_timesheet_sheet_restrict_project/views/hr_timesheet_restrict_project.xml
  hr_timesheet_sheet_restrict_project/views/hr_timesheet_sheet_view.xml
Labels: approved, needs review

#204 [11.0][FIX] hr_timesheet_sheet: wrong decorator
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved

#215 [12.0] crm_timesheet: Migration to 12.0
  crm_timesheet/README.rst
  crm_timesheet/__init__.py
  crm_timesheet/__manifest__.py
  crm_timesheet/i18n/crm_timesheet.pot
  crm_timesheet/i18n/cs_CZ.po
  crm_timesheet/i18n/es.po
  crm_timesheet/i18n/fr.po
  crm_timesheet/i18n/it.po
  crm_timesheet/models/__init__.py
  crm_timesheet/models/account_analytic_line.py
  crm_timesheet/models/crm_lead.py
  crm_timesheet/readme/CONTRIBUTORS.rst
  crm_timesheet/readme/DESCRIPTION.rst
  crm_timesheet/readme/ROADMAP.rst
  crm_timesheet/readme/USAGE.rst
  crm_timesheet/static/description/icon.png
  crm_timesheet/static/description/index.html
  crm_timesheet/tests/__init__.py
  crm_timesheet/tests/test_account_analytic_line.py
  crm_timesheet/views/crm_lead_view.xml
  crm_timesheet/views/hr_timesheet_view.xml
Labels: approved

#217 [12.0] Fix non-English instances
  hr_timesheet_role/__manifest__.py
  hr_timesheet_role/report/report_timesheet_templates.xml
  hr_timesheet_role/views/project_portal_templates.xml
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: approved

#207 [11.0][IMP] hr_timesheet_sheet: fix amount calculation issues + code simplification
  hr_timesheet_sheet/README.rst
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
  hr_timesheet_sheet/models/hr_employee.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
Labels: approved, ready to merge

#219 [12.0][FIX] hr_utilization_report: readme
  hr_utilization_report/README.rst
  hr_utilization_report/readme/ROADMAP.rst
  hr_utilization_report/readme/USAGE.rst
  hr_utilization_report/static/description/index.html
Labels: approved, needs review

#211 [12.0][IMP] hr_timesheet_sheet: fix amount calculation issues + code simplification
  hr_timesheet_sheet/README.rst
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/models/account_analytic_line.py
  hr_timesheet_sheet/models/hr_employee.py
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/readme/DESCRIPTION.rst
  hr_timesheet_sheet/readme/ROADMAP.rst
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
Labels: approved, ready to merge

#221 [12.0][IMP] hr_timesheet_task_required: note about multi-company setting
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: approved
