Repository OCA/timesheet, pull requests merged in 2020-11, with the labels that each got.

#404 [UPD] Brainbean Apps => CorporateHub
  hr_timesheet_task_required/README.rst
Labels: bot is merging ⏳

#405 [UPD] Brainbean Apps => CorporateHub
  hr_timesheet_task_required/README.rst
  hr_timesheet_task_stage/README.rst
  hr_timesheet_task_stage/__manifest__.py
  hr_timesheet_task_stage/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#408 [UPD] Brainbean Apps => CorporateHub
  hr_timesheet_analysis/README.rst
  hr_timesheet_analysis/__manifest__.py
  hr_timesheet_analysis/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet/README.rst
  hr_timesheet_sheet/__manifest__.py
  hr_timesheet_sheet/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_autodraft/README.rst
  hr_timesheet_sheet_autodraft/__manifest__.py
  hr_timesheet_sheet_autodraft/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_autodraft_project/README.rst
  hr_timesheet_sheet_autodraft_project/__manifest__.py
  hr_timesheet_sheet_autodraft_project/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_policy_project_manager/README.rst
  hr_timesheet_sheet_policy_project_manager/__manifest__.py
  hr_timesheet_sheet_policy_project_manager/readme/CONTRIBUTORS.rst
  hr_timesheet_task_domain/README.rst
  hr_timesheet_task_domain/__manifest__.py
  hr_timesheet_task_domain/readme/CONTRIBUTORS.rst
  hr_timesheet_task_required/README.rst
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/readme/CONTRIBUTORS.rst
  hr_timesheet_task_stage/README.rst
  hr_timesheet_task_stage/__manifest__.py
  hr_timesheet_task_stage/readme/CONTRIBUTORS.rst
  sale_timesheet_task_exclude/README.rst
  sale_timesheet_task_exclude/__manifest__.py
  sale_timesheet_task_exclude/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#254 [12.0][ADD] sale_project_timesheet_by_seniority
  sale_project_timesheet_by_seniority/__init__.py
  sale_project_timesheet_by_seniority/__manifest__.py
  sale_project_timesheet_by_seniority/models/__init__.py
  sale_project_timesheet_by_seniority/models/account_analytic_line.py
  sale_project_timesheet_by_seniority/models/hr_employee.py
  sale_project_timesheet_by_seniority/models/hr_employee_seniority_level.py
  sale_project_timesheet_by_seniority/models/product_template.py
  sale_project_timesheet_by_seniority/models/sale.py
  sale_project_timesheet_by_seniority/readme/CONFIGURE.rst
  sale_project_timesheet_by_seniority/readme/CONTRIBUTORS.rst
  sale_project_timesheet_by_seniority/readme/DESCRIPTION.rst
  sale_project_timesheet_by_seniority/readme/USAGE.rst
  sale_project_timesheet_by_seniority/security/ir.model.access.csv
  sale_project_timesheet_by_seniority/static/description/icon.png
  sale_project_timesheet_by_seniority/tests/__init__.py
  sale_project_timesheet_by_seniority/tests/test_sale_project_timesheet_by_seniority.py
  sale_project_timesheet_by_seniority/views/hr_employee_seniority_level.xml
Labels: approved, bot is merging ⏳, ready to merge

#389 [13.0][MIG] sale_timesheet_order_line_sync: Migration to 13.0
  sale_timesheet_order_line_sync/README.rst
  sale_timesheet_order_line_sync/__init__.py
  sale_timesheet_order_line_sync/__manifest__.py
  sale_timesheet_order_line_sync/i18n/es.po
  sale_timesheet_order_line_sync/i18n/sale_timesheet_order_line_sync.pot
  sale_timesheet_order_line_sync/models/__init__.py
  sale_timesheet_order_line_sync/models/project_task.py
  sale_timesheet_order_line_sync/readme/CONTRIBUTORS.rst
  sale_timesheet_order_line_sync/readme/DESCRIPTION.rst
  sale_timesheet_order_line_sync/readme/USAGE.rst
  sale_timesheet_order_line_sync/static/description/icon.png
  sale_timesheet_order_line_sync/static/description/index.html
  sale_timesheet_order_line_sync/tests/__init__.py
  sale_timesheet_order_line_sync/tests/test_sale_timesheet_order_line_sync.py
  setup/sale_timesheet_order_line_sync/odoo/addons/sale_timesheet_order_line_sync
  setup/sale_timesheet_order_line_sync/setup.py
Labels: approved, bot is merging ⏳

#383 [FIX] Fix for issue #382
  hr_timesheet_sheet_attendance/models/hr_timesheet_sheet.py
Labels: approved, bot is merging ⏳, ready to merge

#413 [13.0][FIX] hr_timesheet_sheet: Add review policies for other groups
  hr_timesheet_sheet/README.rst
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/models/res_company.py
  hr_timesheet_sheet/readme/CONFIGURE.rst
  hr_timesheet_sheet/readme/DESCRIPTION.rst
  hr_timesheet_sheet/static/description/index.html
Labels: approved, bot is merging ⏳
