Repository OCA/timesheet, pull requests merged in 2020-10, with the labels that each got.

#395 [12.0][FIX] French translation in hr_timesheet_sheet to avoid a failure on …
  hr_timesheet_sheet/i18n/fr.po
Labels: approved, bot is merging ⏳

#275 [11.0][ADD] sale_timesheet_draft_invoice: create addon
  sale_timesheet_draft_invoice/README.rst
  sale_timesheet_draft_invoice/__init__.py
  sale_timesheet_draft_invoice/__manifest__.py
  sale_timesheet_draft_invoice/models/__init__.py
  sale_timesheet_draft_invoice/models/account_invoice.py
  sale_timesheet_draft_invoice/models/account_invoice_line.py
  sale_timesheet_draft_invoice/readme/CONTRIBUTORS.rst
  sale_timesheet_draft_invoice/readme/DESCRIPTION.rst
  sale_timesheet_draft_invoice/readme/ROADMAP.rst
  sale_timesheet_draft_invoice/tests/__init__.py
  sale_timesheet_draft_invoice/tests/common.py
  sale_timesheet_draft_invoice/tests/test_invoice_lines.py
Labels: bot is merging ⏳

#398 [13.0][FIX] hr_utilization_analysis: use employee instance
  hr_utilization_analysis/__manifest__.py
  hr_utilization_analysis/readme/CONTRIBUTORS.rst
  hr_utilization_analysis/report/hr_utilization_analysis.py
Labels: bot is merging ⏳

#399 [FIX] hr_timesheet_sheet WARNING DB odoo.osv.expression: The domain term '('id', '=', [ID1, ID2,..., IDn])' should use the 'in' or 'not in' operator
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
Labels: approved, bot is merging ⏳, ready to merge
