Repository OCA/timesheet, pull requests merged in 2020-04, with the labels that each got.

#341 [12.0][FIX] hr_timesheet_sheet: drop fuzzy+python-format translations
  hr_timesheet_sheet/i18n/af.po
  hr_timesheet_sheet/i18n/ar.po
  hr_timesheet_sheet/i18n/bg.po
  hr_timesheet_sheet/i18n/bs.po
  hr_timesheet_sheet/i18n/ca.po
  hr_timesheet_sheet/i18n/cs.po
  hr_timesheet_sheet/i18n/da.po
  hr_timesheet_sheet/i18n/de.po
  hr_timesheet_sheet/i18n/el.po
  hr_timesheet_sheet/i18n/en_AU.po
  hr_timesheet_sheet/i18n/en_GB.po
  hr_timesheet_sheet/i18n/es_AR.po
  hr_timesheet_sheet/i18n/es_CL.po
  hr_timesheet_sheet/i18n/es_CR.po
  hr_timesheet_sheet/i18n/es_EC.po
  hr_timesheet_sheet/i18n/es_PE.po
  hr_timesheet_sheet/i18n/es_VE.po
  hr_timesheet_sheet/i18n/et.po
  hr_timesheet_sheet/i18n/eu.po
  hr_timesheet_sheet/i18n/fa.po
  hr_timesheet_sheet/i18n/fi.po
  hr_timesheet_sheet/i18n/fr.po
  hr_timesheet_sheet/i18n/gl.po
  hr_timesheet_sheet/i18n/gu.po
  hr_timesheet_sheet/i18n/he.po
  hr_timesheet_sheet/i18n/hr.po
  hr_timesheet_sheet/i18n/hu.po
  hr_timesheet_sheet/i18n/id.po
  hr_timesheet_sheet/i18n/ja.po
  hr_timesheet_sheet/i18n/ka.po
  hr_timesheet_sheet/i18n/kab.po
  hr_timesheet_sheet/i18n/ko.po
  hr_timesheet_sheet/i18n/lt.po
  hr_timesheet_sheet/i18n/lv.po
  hr_timesheet_sheet/i18n/mk.po
  hr_timesheet_sheet/i18n/mn.po
  hr_timesheet_sheet/i18n/nb.po
  hr_timesheet_sheet/i18n/nl_BE.po
  hr_timesheet_sheet/i18n/pl.po
  hr_timesheet_sheet/i18n/pt.po
  hr_timesheet_sheet/i18n/pt_BR.po
  hr_timesheet_sheet/i18n/ro.po
  hr_timesheet_sheet/i18n/ru.po
  hr_timesheet_sheet/i18n/sk.po
  hr_timesheet_sheet/i18n/sl.po
  hr_timesheet_sheet/i18n/sr@latin.po
  hr_timesheet_sheet/i18n/sv.po
  hr_timesheet_sheet/i18n/th.po
  hr_timesheet_sheet/i18n/tr.po
  hr_timesheet_sheet/i18n/uk.po
  hr_timesheet_sheet/i18n/vi.po
  hr_timesheet_sheet/i18n/zh_CN.po
  hr_timesheet_sheet/i18n/zh_TW.po
Labels: approved, bot is merging ⏳

#304 [12.0][FIX] hr_timesheet_activity_begin_end: error on merge timesheet sheet lines
  hr_timesheet_activity_begin_end/models/account_analytic_line.py
  hr_timesheet_activity_begin_end/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, ready to merge

#343 [12.0][FIX]ca.po file in hr_timesheet_sheet module (WIP)
  hr_timesheet_sheet/i18n/ca.po
Labels: bot is merging ⏳

#338 [12.0][ADD] sale_timesheet_order_line_sync: New module
  sale_timesheet_order_line_sync/README.rst
  sale_timesheet_order_line_sync/__init__.py
  sale_timesheet_order_line_sync/__manifest__.py
  sale_timesheet_order_line_sync/models/__init__.py
  sale_timesheet_order_line_sync/models/project_task.py
  sale_timesheet_order_line_sync/readme/CONTRIBUTORS.rst
  sale_timesheet_order_line_sync/readme/DESCRIPTION.rst
  sale_timesheet_order_line_sync/readme/USAGE.rst
  sale_timesheet_order_line_sync/static/description/icon.png
  sale_timesheet_order_line_sync/static/description/index.html
  sale_timesheet_order_line_sync/tests/__init__.py
  sale_timesheet_order_line_sync/tests/test_sale_timesheet_order_line_sync.py
Labels: approved, bot is merging ⏳, ready to merge

#346 [13.0][FIX] known_third_party: include openupgradelib
  .isort.cfg
Labels: bot is merging ⏳

#347 [13.0][FIX] hr_timesheet_sheet: openupgrade
  hr_timesheet_sheet/migrations/13.0.1.0.0/post-migration.py
  hr_timesheet_sheet/migrations/13.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#323 [13.0][MIG] hr_timesheet_task_domain: Migration to 13.0
  hr_timesheet_task_domain/README.rst
  hr_timesheet_task_domain/__init__.py
  hr_timesheet_task_domain/__manifest__.py
  hr_timesheet_task_domain/i18n/de.po
  hr_timesheet_task_domain/i18n/es.po
  hr_timesheet_task_domain/i18n/hr_timesheet_task_domain.pot
  hr_timesheet_task_domain/models/__init__.py
  hr_timesheet_task_domain/models/account_analytic_line.py
  hr_timesheet_task_domain/readme/CONTRIBUTORS.rst
  hr_timesheet_task_domain/readme/DESCRIPTION.rst
  hr_timesheet_task_domain/static/description/icon.png
  hr_timesheet_task_domain/static/description/index.html
  hr_timesheet_task_domain/tests/__init__.py
  hr_timesheet_task_domain/tests/test_hr_timesheet_task_domain.py
Labels: bot is merging ⏳
