Repository OCA/timesheet, pull requests merged in 2020-07, with the labels that each got.

#319 [13.0[[MIG] hr_timesheet_task_stage: Migration to 13.0
  hr_timesheet_task_stage/README.rst
  hr_timesheet_task_stage/__init__.py
  hr_timesheet_task_stage/__manifest__.py
  hr_timesheet_task_stage/i18n/de.po
  hr_timesheet_task_stage/i18n/es.po
  hr_timesheet_task_stage/i18n/hr_timesheet_task_stage.pot
  hr_timesheet_task_stage/models/__init__.py
  hr_timesheet_task_stage/models/account_analytic_line.py
  hr_timesheet_task_stage/readme/CONTRIBUTORS.rst
  hr_timesheet_task_stage/readme/DESCRIPTION.rst
  hr_timesheet_task_stage/static/description/icon.png
  hr_timesheet_task_stage/static/description/index.html
  hr_timesheet_task_stage/tests/__init__.py
  hr_timesheet_task_stage/tests/test_hr_timesheet_task_stage.py
  hr_timesheet_task_stage/views/account_analytic_line.xml
  oca_dependencies.txt
  setup/hr_timesheet_task_stage/odoo/addons/hr_timesheet_task_stage
  setup/hr_timesheet_task_stage/setup.py
Labels: bot is merging ⏳

#307 [12.0][IMP] hr_timesheet_activity_begin_end: sort timesheets by date and time
  hr_timesheet_activity_begin_end/models/account_analytic_line.py
  hr_timesheet_activity_begin_end/views/hr_timesheet_sheet.xml
Labels: approved, bot is merging ⏳, ready to merge

#344 [13.0][MIG] hr_timesheet_activity_begin_end: Migration to 13.0
  hr_timesheet_activity_begin_end/README.rst
  hr_timesheet_activity_begin_end/__init__.py
  hr_timesheet_activity_begin_end/__manifest__.py
  hr_timesheet_activity_begin_end/i18n/cs_CZ.po
  hr_timesheet_activity_begin_end/i18n/de.po
  hr_timesheet_activity_begin_end/i18n/es.po
  hr_timesheet_activity_begin_end/i18n/fr.po
  hr_timesheet_activity_begin_end/i18n/hr_timesheet_activity_begin_end.pot
  hr_timesheet_activity_begin_end/i18n/it.po
  hr_timesheet_activity_begin_end/i18n/nl_NL.po
  hr_timesheet_activity_begin_end/models/__init__.py
  hr_timesheet_activity_begin_end/models/account_analytic_line.py
  hr_timesheet_activity_begin_end/readme/CONTRIBUTORS.rst
  hr_timesheet_activity_begin_end/readme/DESCRIPTION.rst
  hr_timesheet_activity_begin_end/static/description/icon.png
  hr_timesheet_activity_begin_end/static/description/index.html
  hr_timesheet_activity_begin_end/tests/__init__.py
  hr_timesheet_activity_begin_end/tests/test_timesheet_begin_end.py
  hr_timesheet_activity_begin_end/views/hr_analytic_timesheet.xml
  hr_timesheet_activity_begin_end/views/hr_timesheet_sheet.xml
  setup/hr_timesheet_activity_begin_end/setup.py
Labels: approved, bot is merging ⏳

#360 [13.0][MIG] hr_utilization_analysis
  hr_utilization_analysis/README.rst
  hr_utilization_analysis/__init__.py
  hr_utilization_analysis/__manifest__.py
  hr_utilization_analysis/i18n/de.po
  hr_utilization_analysis/i18n/es.po
  hr_utilization_analysis/i18n/hr_utilization_analysis.pot
  hr_utilization_analysis/i18n/pt.po
  hr_utilization_analysis/readme/CONTRIBUTORS.rst
  hr_utilization_analysis/readme/DESCRIPTION.rst
  hr_utilization_analysis/readme/USAGE.rst
  hr_utilization_analysis/report/__init__.py
  hr_utilization_analysis/report/hr_utilization_analysis.py
  hr_utilization_analysis/report/hr_utilization_analysis.xml
  hr_utilization_analysis/static/description/icon.png
  hr_utilization_analysis/static/description/index.html
  hr_utilization_analysis/tests/__init__.py
  hr_utilization_analysis/tests/test_hr_utilization_analysis.py
  hr_utilization_analysis/views/hr_department.xml
  hr_utilization_analysis/views/hr_employee.xml
  hr_utilization_analysis/wizards/__init__.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.xml
  setup/hr_utilization_analysis/odoo/addons/hr_utilization_analysis
  setup/hr_utilization_analysis/setup.py
Labels: bot is merging ⏳

#358 [13.0][MIG] hr_timesheet_analysis
  hr_timesheet_analysis/README.rst
  hr_timesheet_analysis/__init__.py
  hr_timesheet_analysis/__manifest__.py
  hr_timesheet_analysis/i18n/de.po
  hr_timesheet_analysis/i18n/es.po
  hr_timesheet_analysis/i18n/hr_timesheet_analysis.pot
  hr_timesheet_analysis/readme/CONTRIBUTORS.rst
  hr_timesheet_analysis/readme/DESCRIPTION.rst
  hr_timesheet_analysis/static/description/icon.png
  hr_timesheet_analysis/static/description/index.html
  hr_timesheet_analysis/views/account_analytic_line.xml
  setup/hr_timesheet_analysis/odoo/addons/hr_timesheet_analysis
  setup/hr_timesheet_analysis/setup.py
Labels: bot is merging ⏳

#366 [13.0][MIG] hr_timesheet_sheet_policy_project_manager
  hr_timesheet_sheet_policy_project_manager/README.rst
  hr_timesheet_sheet_policy_project_manager/__init__.py
  hr_timesheet_sheet_policy_project_manager/__manifest__.py
  hr_timesheet_sheet_policy_project_manager/i18n/es.po
  hr_timesheet_sheet_policy_project_manager/i18n/hr_timesheet_sheet_policy_project_manager.pot
  hr_timesheet_sheet_policy_project_manager/models/__init__.py
  hr_timesheet_sheet_policy_project_manager/models/account_analytic_line.py
  hr_timesheet_sheet_policy_project_manager/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_policy_project_manager/models/res_company.py
  hr_timesheet_sheet_policy_project_manager/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_policy_project_manager/readme/DESCRIPTION.rst
  hr_timesheet_sheet_policy_project_manager/static/description/icon.png
  hr_timesheet_sheet_policy_project_manager/static/description/index.html
  hr_timesheet_sheet_policy_project_manager/tests/__init__.py
  hr_timesheet_sheet_policy_project_manager/tests/test_hr_timesheet_sheet_policy_project_manager.py
  hr_timesheet_sheet_policy_project_manager/views/hr_timesheet_sheet.xml
  setup/hr_timesheet_sheet_policy_project_manager/odoo/addons/hr_timesheet_sheet_policy_project_manager
  setup/hr_timesheet_sheet_policy_project_manager/setup.py
Labels: approved, bot is merging ⏳

#368 [FIX] hr_timesheet_sheet_autodraft_project: add dependency on hr_timesheet_sheet_autodraft
  hr_timesheet_sheet_autodraft_project/__manifest__.py
Labels: bot is merging ⏳
