Repository OCA/timesheet, pull requests merged in 2020-09, with the labels that each got.

#348 [10.0][IMP] hr_timesheet_task: allow to change the condition to get the line to update when editing a timesheet cell
  hr_timesheet_task/static/src/js/timesheet.js
Labels: approved, bot is merging ⏳, ready to merge

#384 Added explanation on how to use the module
  hr_timesheet_analysis/readme/USAGE.rst
Labels: approved, bot is merging ⏳, ready to merge

#393 sale_timesheet_limit_date: fix tests (close #391)
  sale_timesheet_limit_date/tests/test_sale_lines.py
Labels: bot is merging ⏳

#392 [13.0][MIG] crm_timesheet: Migration to 13.0
  crm_timesheet/README.rst
  crm_timesheet/__init__.py
  crm_timesheet/__manifest__.py
  crm_timesheet/i18n/crm_timesheet.pot
  crm_timesheet/i18n/cs_CZ.po
  crm_timesheet/i18n/de.po
  crm_timesheet/i18n/es.po
  crm_timesheet/i18n/fr.po
  crm_timesheet/i18n/it.po
  crm_timesheet/i18n/pt.po
  crm_timesheet/i18n/pt_BR.po
  crm_timesheet/models/__init__.py
  crm_timesheet/models/account_analytic_line.py
  crm_timesheet/models/crm_lead.py
  crm_timesheet/readme/CONTRIBUTORS.rst
  crm_timesheet/readme/DESCRIPTION.rst
  crm_timesheet/readme/ROADMAP.rst
  crm_timesheet/readme/USAGE.rst
  crm_timesheet/static/description/icon.png
  crm_timesheet/static/description/index.html
  crm_timesheet/tests/__init__.py
  crm_timesheet/tests/test_account_analytic_line.py
  crm_timesheet/views/crm_lead_view.xml
  crm_timesheet/views/hr_timesheet_view.xml
  crm_timesheet/wizards/__init__.py
  crm_timesheet/wizards/hr_timesheet_switch.py
  setup/crm_timesheet/odoo/addons/crm_timesheet
  setup/crm_timesheet/setup.py
Labels: approved, bot is merging ⏳

#379 [12.0] [ADD] sale_timesheet_purchase: Backport the module from v13 to v12.
  sale_timesheet_purchase/README.rst
  sale_timesheet_purchase/__init__.py
  sale_timesheet_purchase/__manifest__.py
  sale_timesheet_purchase/controllers/__init__.py
  sale_timesheet_purchase/controllers/main.py
  sale_timesheet_purchase/readme/CONTRIBUTORS.rst
  sale_timesheet_purchase/readme/CREDITS.rst
  sale_timesheet_purchase/readme/DESCRIPTION.rst
  sale_timesheet_purchase/static/description/index.html
Labels: approved, bot is merging ⏳
