Repository OCA/timesheet, pull requests merged in 2021-01, with the labels that each got.

#420 [13.0][FIX] Typo
  hr_timesheet_sheet/views/account_analytic_line_views.xml
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#418 [FIX] sale_timesheet_line_exclude: user friendly Non-billable label
  sale_timesheet_line_exclude/i18n/de.po
  sale_timesheet_line_exclude/i18n/es.po
  sale_timesheet_line_exclude/i18n/sale_timesheet_line_exclude.pot
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/readme/USAGE.rst
Labels: approved

#417 [FIX] sale_timesheet_task_exclude: use the clearer Non-billable label
  sale_timesheet_task_exclude/i18n/de.po
  sale_timesheet_task_exclude/i18n/es.po
  sale_timesheet_task_exclude/i18n/sale_timesheet_task_exclude.pot
  sale_timesheet_task_exclude/models/project_task.py
  sale_timesheet_task_exclude/readme/USAGE.rst
Labels: approved

#46 [ADD] hr_timesheet_print_employee_timesheet
  hr_timesheet_print_employee_timesheet/README.rst
  hr_timesheet_print_employee_timesheet/__init__.py
  hr_timesheet_print_employee_timesheet/__openerp__.py
  hr_timesheet_print_employee_timesheet/i18n/hr_timesheet_print_employee_timesheet.pot
  hr_timesheet_print_employee_timesheet/i18n/nl.po
  hr_timesheet_print_employee_timesheet/model/__init__.py
  hr_timesheet_print_employee_timesheet/model/hr_analytic_timesheet.py
  hr_timesheet_print_employee_timesheet/model/report.py
  hr_timesheet_print_employee_timesheet/report/hr_analytical_timesheet_employees.xml
  hr_timesheet_print_employee_timesheet/static/description/icon.png
  hr_timesheet_print_employee_timesheet/tests/__init__.py
  hr_timesheet_print_employee_timesheet/tests/test_hr_timesheet_print_employee_timesheet.py
  hr_timesheet_print_employee_timesheet/wizard/__init__.py
  hr_timesheet_print_employee_timesheet/wizard/hr_analytical_timesheet_employees.py
  hr_timesheet_print_employee_timesheet/wizard/hr_analytical_timesheet_employees.xml
Labels: needs review
