Repository OCA/timesheet, pull requests merged in 2022-08, with the labels that each got.

#473 [14.0] [mig] hr_utilization_report
  hr_utilization_report/README.rst
  hr_utilization_report/__init__.py
  hr_utilization_report/__manifest__.py
  hr_utilization_report/i18n/de.po
  hr_utilization_report/i18n/es.po
  hr_utilization_report/i18n/fr.po
  hr_utilization_report/i18n/hr_utilization_report.pot
  hr_utilization_report/readme/CONTRIBUTORS.rst
  hr_utilization_report/readme/DESCRIPTION.rst
  hr_utilization_report/readme/ROADMAP.rst
  hr_utilization_report/readme/USAGE.rst
  hr_utilization_report/report/__init__.py
  hr_utilization_report/report/hr_utilization_report.py
  hr_utilization_report/report/hr_utilization_report.xml
  hr_utilization_report/security/ir.model.access.csv
  hr_utilization_report/static/description/icon.png
  hr_utilization_report/static/description/index.html
  hr_utilization_report/tests/__init__.py
  hr_utilization_report/tests/test_hr_utilization_report.py
  hr_utilization_report/views/hr_department.xml
  hr_utilization_report/views/hr_employee.xml
  hr_utilization_report/wizards/__init__.py
  hr_utilization_report/wizards/hr_utilization_report_wizard.py
  hr_utilization_report/wizards/hr_utilization_report_wizard.xml
  setup/hr_utilization_report/odoo/addons/hr_utilization_report
  setup/hr_utilization_report/setup.py
Labels: approved, bot is merging ⏳

#513 [14.0][FIX] Contributors formatting
  hr_timesheet_analysis/readme/CONTRIBUTORS.rst
  hr_utilization_report/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#495 [14.0][ADD] hr_timesheet_milestone
  hr_timesheet_report_milestone/README.rst
  hr_timesheet_report_milestone/__init__.py
  hr_timesheet_report_milestone/__manifest__.py
  hr_timesheet_report_milestone/i18n/hr_timesheet_milestone.pot
  hr_timesheet_report_milestone/i18n/it.po
  hr_timesheet_report_milestone/models/__init__.py
  hr_timesheet_report_milestone/models/account_analytic_line.py
  hr_timesheet_report_milestone/readme/CONTRIBUTORS.rst
  hr_timesheet_report_milestone/readme/DESCRIPTION.rst
  hr_timesheet_report_milestone/readme/USAGE.rst
  hr_timesheet_report_milestone/report/__init__.py
  hr_timesheet_report_milestone/report/hr_timesheet_report.py
  hr_timesheet_report_milestone/tests/__init__.py
  hr_timesheet_report_milestone/tests/test_hr_timesheet_report_milestone.py
  hr_timesheet_report_milestone/wizards/__init__.py
  hr_timesheet_report_milestone/wizards/hr_timesheet_report_wizard.py
  hr_timesheet_report_milestone/wizards/hr_timesheet_report_wizard.xml
  setup/hr_timesheet_report_milestone/odoo/addons/hr_timesheet_report_milestone
  setup/hr_timesheet_report_milestone/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#510 [14.0][MIG] sale_timesheet_line_exclude
  requirements.txt
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__init__.py
  sale_timesheet_line_exclude/__manifest__.py
  sale_timesheet_line_exclude/hooks.py
  sale_timesheet_line_exclude/i18n/de.po
  sale_timesheet_line_exclude/i18n/es.po
  sale_timesheet_line_exclude/i18n/fr.po
  sale_timesheet_line_exclude/i18n/sale_timesheet_line_exclude.pot
  sale_timesheet_line_exclude/models/__init__.py
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.rst
  sale_timesheet_line_exclude/readme/DESCRIPTION.rst
  sale_timesheet_line_exclude/readme/USAGE.rst
  sale_timesheet_line_exclude/static/description/icon.png
  sale_timesheet_line_exclude/static/description/index.html
  sale_timesheet_line_exclude/tests/__init__.py
  sale_timesheet_line_exclude/tests/test_sale_timesheet_line_exclude.py
  sale_timesheet_line_exclude/views/account_analytic_line.xml
  sale_timesheet_line_exclude/views/project_task.xml
  setup/sale_timesheet_line_exclude/odoo/addons/sale_timesheet_line_exclude
  setup/sale_timesheet_line_exclude/setup.py
Labels: approved, bot is merging ⏳

#496 [14.0][NEW] hr_timesheet_time_restriction
  hr_timesheet_time_restriction/README.rst
  hr_timesheet_time_restriction/__init__.py
  hr_timesheet_time_restriction/__manifest__.py
  hr_timesheet_time_restriction/models/__init__.py
  hr_timesheet_time_restriction/models/account_analytic_line.py
  hr_timesheet_time_restriction/models/project_project.py
  hr_timesheet_time_restriction/models/res_config_settings.py
  hr_timesheet_time_restriction/readme/CONFIGURE.rst
  hr_timesheet_time_restriction/readme/CONTRIBUTORS.rst
  hr_timesheet_time_restriction/readme/CREDITS.rst
  hr_timesheet_time_restriction/readme/DESCRIPTION.rst
  hr_timesheet_time_restriction/security/res_groups.xml
  hr_timesheet_time_restriction/static/description/icon.png
  hr_timesheet_time_restriction/tests/__init__.py
  hr_timesheet_time_restriction/tests/test_hr_timesheet_time_restriction.py
  hr_timesheet_time_restriction/views/project_project_view.xml
  hr_timesheet_time_restriction/views/res_config_settings_view.xml
  setup/hr_timesheet_time_restriction/odoo/addons/hr_timesheet_time_restriction
  setup/hr_timesheet_time_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#487 [14.0][NEW] hr_timesheet_purchase_order
  hr_timesheet_purchase_order/README.rst
  hr_timesheet_purchase_order/__init__.py
  hr_timesheet_purchase_order/__manifest__.py
  hr_timesheet_purchase_order/data/ir_actions_server.xml
  hr_timesheet_purchase_order/models/__init__.py
  hr_timesheet_purchase_order/models/hr_employee_base.py
  hr_timesheet_purchase_order/models/hr_timesheet_sheet.py
  hr_timesheet_purchase_order/models/purchase_order.py
  hr_timesheet_purchase_order/models/res_company.py
  hr_timesheet_purchase_order/models/res_config_settings.py
  hr_timesheet_purchase_order/readme/CONFIGURE.rst
  hr_timesheet_purchase_order/readme/CONTRIBUTORS.rst
  hr_timesheet_purchase_order/readme/CREDITS.rst
  hr_timesheet_purchase_order/readme/DESCRIPTION.rst
  hr_timesheet_purchase_order/readme/USAGE.rst
  hr_timesheet_purchase_order/static/description/icon.png
  hr_timesheet_purchase_order/tests/__init__.py
  hr_timesheet_purchase_order/tests/test_create_timesheet_purchase_order.py
  hr_timesheet_purchase_order/views/hr_employee_view.xml
  hr_timesheet_purchase_order/views/hr_timesheet_sheet_view.xml
  hr_timesheet_purchase_order/views/purchase_order_view.xml
  hr_timesheet_purchase_order/views/res_config_settings_view.xml
  setup/hr_timesheet_purchase_order/odoo/addons/hr_timesheet_purchase_order
  setup/hr_timesheet_purchase_order/setup.py
Labels: approved, bot is merging ⏳
