Repository OCA/timesheet, pull requests merged in 2022-11, with the labels that each got.

#517 [15.0][MIG] hr_timesheet_activity_begin_end
  hr_timesheet_begin_end/README.rst
  hr_timesheet_begin_end/__init__.py
  hr_timesheet_begin_end/__manifest__.py
  hr_timesheet_begin_end/i18n/cs_CZ.po
  hr_timesheet_begin_end/i18n/de.po
  hr_timesheet_begin_end/i18n/es.po
  hr_timesheet_begin_end/i18n/fr.po
  hr_timesheet_begin_end/i18n/hr_timesheet_begin_end.pot
  hr_timesheet_begin_end/i18n/it.po
  hr_timesheet_begin_end/i18n/nl_NL.po
  hr_timesheet_begin_end/i18n/sv.po
  hr_timesheet_begin_end/i18n/sv_SE.po
  hr_timesheet_begin_end/models/__init__.py
  hr_timesheet_begin_end/models/account_analytic_line.py
  hr_timesheet_begin_end/readme/CONTRIBUTORS.rst
  hr_timesheet_begin_end/readme/DESCRIPTION.rst
  hr_timesheet_begin_end/static/description/icon.png
  hr_timesheet_begin_end/static/description/index.html
  hr_timesheet_begin_end/tests/__init__.py
  hr_timesheet_begin_end/tests/test_timesheet_begin_end.py
  hr_timesheet_begin_end/views/hr_analytic_timesheet.xml
  hr_timesheet_sheet_begin_end/README.rst
  hr_timesheet_sheet_begin_end/__init__.py
  hr_timesheet_sheet_begin_end/__manifest__.py
  hr_timesheet_sheet_begin_end/i18n/cs_CZ.po
  hr_timesheet_sheet_begin_end/i18n/de.po
  hr_timesheet_sheet_begin_end/i18n/es.po
  hr_timesheet_sheet_begin_end/i18n/fr.po
  hr_timesheet_sheet_begin_end/i18n/hr_timesheet_sheet_begin_end.pot
  hr_timesheet_sheet_begin_end/i18n/it.po
  hr_timesheet_sheet_begin_end/i18n/nl_NL.po
  hr_timesheet_sheet_begin_end/i18n/sv.po
  hr_timesheet_sheet_begin_end/i18n/sv_SE.po
  hr_timesheet_sheet_begin_end/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_begin_end/readme/DESCRIPTION.rst
  hr_timesheet_sheet_begin_end/static/description/icon.png
  hr_timesheet_sheet_begin_end/static/description/index.html
  hr_timesheet_sheet_begin_end/views/hr_timesheet_sheet.xml
  setup/_metapackage/setup.py
  setup/hr_timesheet_begin_end/odoo/addons/hr_timesheet_begin_end
  setup/hr_timesheet_begin_end/setup.py
  setup/hr_timesheet_sheet_begin_end/odoo/addons/hr_timesheet_sheet_begin_end
  setup/hr_timesheet_sheet_begin_end/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#538 [14.0][FIX] sale_timesheet_line_exclude, remove non_allow_billable inheritance
  .copier-answers.yml
  .pre-commit-config.yaml
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.rst
  sale_timesheet_line_exclude/views/account_analytic_line.xml
Labels: approved, ready to merge, bot is merging ⏳

#544 [15.0][MIG] crm_timesheet: Migration to version 15.0
  crm_timesheet/README.rst
  crm_timesheet/__init__.py
  crm_timesheet/__manifest__.py
  crm_timesheet/i18n/crm_timesheet.pot
  crm_timesheet/i18n/cs_CZ.po
  crm_timesheet/i18n/de.po
  crm_timesheet/i18n/es.po
  crm_timesheet/i18n/fr.po
  crm_timesheet/i18n/it.po
  crm_timesheet/i18n/nl.po
  crm_timesheet/i18n/pt.po
  crm_timesheet/i18n/pt_BR.po
  crm_timesheet/models/__init__.py
  crm_timesheet/models/account_analytic_line.py
  crm_timesheet/models/crm_lead.py
  crm_timesheet/readme/CONTRIBUTORS.rst
  crm_timesheet/readme/DESCRIPTION.rst
  crm_timesheet/readme/ROADMAP.rst
  crm_timesheet/readme/USAGE.rst
  crm_timesheet/security/ir.model.access.csv
  crm_timesheet/static/description/icon.png
  crm_timesheet/static/description/index.html
  crm_timesheet/tests/__init__.py
  crm_timesheet/tests/test_account_analytic_line.py
  crm_timesheet/views/crm_lead_view.xml
  crm_timesheet/views/hr_timesheet_view.xml
  crm_timesheet/wizards/__init__.py
  crm_timesheet/wizards/hr_timesheet_switch.py
  setup/crm_timesheet/odoo/addons/crm_timesheet
  setup/crm_timesheet/setup.py
Labels: bot is merging ⏳

#542 [14.0] mig hr timesheet sheet activity
  hr_timesheet_sheet_activity/README.rst
  hr_timesheet_sheet_activity/__init__.py
  hr_timesheet_sheet_activity/__manifest__.py
  hr_timesheet_sheet_activity/data/hr_timesheet_sheet_activity_data.xml
  hr_timesheet_sheet_activity/i18n/es.po
  hr_timesheet_sheet_activity/i18n/hr_timesheet_sheet_activity.pot
  hr_timesheet_sheet_activity/i18n/nl_NL.po
  hr_timesheet_sheet_activity/i18n/pt.po
  hr_timesheet_sheet_activity/models/__init__.py
  hr_timesheet_sheet_activity/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_activity/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_activity/readme/DESCRIPTION.rst
  hr_timesheet_sheet_activity/static/description/icon.png
  hr_timesheet_sheet_activity/static/description/index.html
  hr_timesheet_sheet_activity/tests/__init__.py
  hr_timesheet_sheet_activity/tests/test_hr_timesheet_sheet_activity.py
  hr_timesheet_sheet_activity/views/mail_activity.xml
  setup/hr_timesheet_sheet_activity/odoo/addons/hr_timesheet_sheet_activity
  setup/hr_timesheet_sheet_activity/setup.py
Labels: approved, bot is merging ⏳
