Repository OCA/timesheet, pull requests merged in 2022-03, with the labels that each got.

#430 [12.0][ADD] hr_timesheet_portal
  hr_timesheet_portal/README.rst
  hr_timesheet_portal/__init__.py
  hr_timesheet_portal/__manifest__.py
  hr_timesheet_portal/demo/hr_timesheet_portal.xml
  hr_timesheet_portal/readme/CONFIGURE.rst
  hr_timesheet_portal/readme/CONTRIBUTORS.rst
  hr_timesheet_portal/readme/DESCRIPTION.rst
  hr_timesheet_portal/readme/newsfragments/.gitkeep
  hr_timesheet_portal/security/hr_timesheet_portal_security.xml
  hr_timesheet_portal/security/ir.model.access.csv
  hr_timesheet_portal/static/src/css/hr_timesheet_portal.css
  hr_timesheet_portal/static/src/js/hr_timesheet_portal.js
  hr_timesheet_portal/templates/assets.xml
  hr_timesheet_portal/templates/portal.xml
Labels: needs fixing, approved, bot is merging ⏳

#477 [14.0][FIX] Do not try to remove invoiced lines supersedes 450
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved, ready to merge, bot is merging ⏳

#475 {14.0}[PORT] 363 from 12.0 [FIX] project_timesheet_time_control: incompatible with sale_timesheet_rounded
  sale_timesheet_rounded/models/account_analytic_line.py
Labels: approved, ready to merge, bot is merging ⏳

#472 [14.0] [mig] hr_timesheet_report
  hr_timesheet_report/README.rst
  hr_timesheet_report/__init__.py
  hr_timesheet_report/__manifest__.py
  hr_timesheet_report/i18n/hr_timesheet_report.pot
  hr_timesheet_report/models/__init__.py
  hr_timesheet_report/models/account_analytic_line.py
  hr_timesheet_report/readme/CONTRIBUTORS.rst
  hr_timesheet_report/readme/DESCRIPTION.rst
  hr_timesheet_report/readme/USAGE.rst
  hr_timesheet_report/report/__init__.py
  hr_timesheet_report/report/hr_timesheet_report.py
  hr_timesheet_report/report/hr_timesheet_report.xml
  hr_timesheet_report/security/ir.model.access.csv
  hr_timesheet_report/static/description/icon.png
  hr_timesheet_report/static/description/index.html
  hr_timesheet_report/tests/__init__.py
  hr_timesheet_report/tests/test_hr_timesheet_report.py
  hr_timesheet_report/views/account_analytic_line.xml
  hr_timesheet_report/wizards/__init__.py
  hr_timesheet_report/wizards/hr_timesheet_report_wizard.py
  hr_timesheet_report/wizards/hr_timesheet_report_wizard.xml
  setup/hr_timesheet_report/odoo/addons/hr_timesheet_report
  setup/hr_timesheet_report/setup.py
Labels: approved, bot is merging ⏳

#476 [14.0][FIX] hr_timesheet_sheet - Do not merge invoiced timesheet lines
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved, bot is merging ⏳
