Repository OCA/timesheet, pull requests merged in 2022-10, with the labels that each got.

#508 [15.0] [MIG] hr_timesheet_time_type
  hr_timesheet_time_type/README.rst
  hr_timesheet_time_type/__init__.py
  hr_timesheet_time_type/__manifest__.py
  hr_timesheet_time_type/i18n/hr_timesheet_time_type.pot
  hr_timesheet_time_type/models/__init__.py
  hr_timesheet_time_type/models/account_analytic_line.py
  hr_timesheet_time_type/models/project_time_type.py
  hr_timesheet_time_type/readme/CONTRIBUTORS.rst
  hr_timesheet_time_type/readme/CREDITS.rst
  hr_timesheet_time_type/readme/DESCRIPTION.rst
  hr_timesheet_time_type/security/ir.model.access.csv
  hr_timesheet_time_type/static/description/icon.png
  hr_timesheet_time_type/static/description/index.html
  hr_timesheet_time_type/views/account_analytic_line_view.xml
  hr_timesheet_time_type/views/project_time_type_view.xml
  setup/hr_timesheet_time_type/odoo/addons/hr_timesheet_time_type
  setup/hr_timesheet_time_type/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#515 [15.0][MIG] sale_timesheet_line_exclude
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__init__.py
  sale_timesheet_line_exclude/__manifest__.py
  sale_timesheet_line_exclude/i18n/de.po
  sale_timesheet_line_exclude/i18n/es.po
  sale_timesheet_line_exclude/i18n/fr.po
  sale_timesheet_line_exclude/i18n/sale_timesheet_line_exclude.pot
  sale_timesheet_line_exclude/models/__init__.py
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.rst
  sale_timesheet_line_exclude/readme/DESCRIPTION.rst
  sale_timesheet_line_exclude/readme/USAGE.rst
  sale_timesheet_line_exclude/static/description/icon.png
  sale_timesheet_line_exclude/static/description/index.html
  sale_timesheet_line_exclude/tests/__init__.py
  sale_timesheet_line_exclude/tests/test_sale_timesheet_line_exclude.py
  sale_timesheet_line_exclude/views/account_analytic_line.xml
  sale_timesheet_line_exclude/views/project_task.xml
  setup/sale_timesheet_line_exclude/odoo/addons/sale_timesheet_line_exclude
  setup/sale_timesheet_line_exclude/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#500 [15.0][MIG] hr_timesheet_task_stage: Migration to 15.0
  hr_timesheet_task_stage/README.rst
  hr_timesheet_task_stage/__init__.py
  hr_timesheet_task_stage/__manifest__.py
  hr_timesheet_task_stage/i18n/de.po
  hr_timesheet_task_stage/i18n/es.po
  hr_timesheet_task_stage/i18n/fr.po
  hr_timesheet_task_stage/i18n/he_IL.po
  hr_timesheet_task_stage/i18n/hr_timesheet_task_stage.pot
  hr_timesheet_task_stage/i18n/sv.po
  hr_timesheet_task_stage/models/__init__.py
  hr_timesheet_task_stage/models/account_analytic_line.py
  hr_timesheet_task_stage/readme/CONTRIBUTORS.rst
  hr_timesheet_task_stage/readme/DESCRIPTION.rst
  hr_timesheet_task_stage/static/description/icon.png
  hr_timesheet_task_stage/static/description/index.html
  hr_timesheet_task_stage/tests/__init__.py
  hr_timesheet_task_stage/tests/test_hr_timesheet_task_stage.py
  hr_timesheet_task_stage/views/account_analytic_line.xml
  setup/hr_timesheet_task_stage/odoo/addons/hr_timesheet_task_stage
  setup/hr_timesheet_task_stage/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#522 [14.0][ADD] hr_timesheet_employee_analytic_tag: New addon
  hr_timesheet_employee_analytic_tag/README.rst
  hr_timesheet_employee_analytic_tag/__init__.py
  hr_timesheet_employee_analytic_tag/__manifest__.py
  hr_timesheet_employee_analytic_tag/i18n/es.po
  hr_timesheet_employee_analytic_tag/i18n/hr_timesheet_employee_analytic_tag.pot
  hr_timesheet_employee_analytic_tag/models/__init__.py
  hr_timesheet_employee_analytic_tag/models/account_analytic_line.py
  hr_timesheet_employee_analytic_tag/models/hr_employee.py
  hr_timesheet_employee_analytic_tag/readme/CONFIGURE.rst
  hr_timesheet_employee_analytic_tag/readme/CONTRIBUTORS.rst
  hr_timesheet_employee_analytic_tag/readme/DESCRIPTION.rst
  hr_timesheet_employee_analytic_tag/readme/USAGE.rst
  hr_timesheet_employee_analytic_tag/static/description/icon.png
  hr_timesheet_employee_analytic_tag/static/description/index.html
  hr_timesheet_employee_analytic_tag/tests/__init__.py
  hr_timesheet_employee_analytic_tag/tests/test_hr_timesheet_employee_analytic_tag.py
  hr_timesheet_employee_analytic_tag/views/hr_employee_view.xml
  setup/hr_timesheet_employee_analytic_tag/odoo/addons/hr_timesheet_employee_analytic_tag
  setup/hr_timesheet_employee_analytic_tag/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#504 [15.0][MIG] sale_timesheet_task_exclude
  sale_timesheet_task_exclude/README.rst
  sale_timesheet_task_exclude/__init__.py
  sale_timesheet_task_exclude/__manifest__.py
  sale_timesheet_task_exclude/i18n/de.po
  sale_timesheet_task_exclude/i18n/es.po
  sale_timesheet_task_exclude/i18n/sale_timesheet_task_exclude.pot
  sale_timesheet_task_exclude/models/__init__.py
  sale_timesheet_task_exclude/models/project_task.py
  sale_timesheet_task_exclude/readme/CONTRIBUTORS.rst
  sale_timesheet_task_exclude/readme/DESCRIPTION.rst
  sale_timesheet_task_exclude/readme/ROADMAP.rst
  sale_timesheet_task_exclude/readme/USAGE.rst
  sale_timesheet_task_exclude/static/description/icon.png
  sale_timesheet_task_exclude/static/description/index.html
  sale_timesheet_task_exclude/tests/__init__.py
  sale_timesheet_task_exclude/tests/test_sale_timesheet_exclude_task.py
  sale_timesheet_task_exclude/views/project_task.xml
  setup/sale_timesheet_task_exclude/odoo/addons/sale_timesheet_task_exclude
  setup/sale_timesheet_task_exclude/setup.py
Labels: bot is merging ⏳

#416 [13.0][IMP] hr_utilization_analysis: add date_range widget for usability
  hr_utilization_analysis/__manifest__.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.xml
Labels: bot is merging ⏳

#493 [15.0][MIG] hr_employee_product
  hr_employee_product/README.rst
  hr_employee_product/__init__.py
  hr_employee_product/__manifest__.py
  hr_employee_product/i18n/cs_CZ.po
  hr_employee_product/i18n/es.po
  hr_employee_product/i18n/fr.po
  hr_employee_product/i18n/hr_employee_product.pot
  hr_employee_product/i18n/it.po
  hr_employee_product/i18n/pt.po
  hr_employee_product/model/__init__.py
  hr_employee_product/model/product.py
  hr_employee_product/readme/CONTRIBUTORS.rst
  hr_employee_product/readme/DESCRIPTION.rst
  hr_employee_product/readme/USAGE.rst
  hr_employee_product/security/product_security.xml
  hr_employee_product/static/description/icon.png
  hr_employee_product/static/description/index.html
  hr_employee_product/tests/__init__.py
  hr_employee_product/tests/test_hr_employee_product.py
  hr_employee_product/view/product.xml
  setup/hr_employee_product/odoo/addons/hr_employee_product
  setup/hr_employee_product/setup.py
Labels: bot is merging ⏳

#531 [14.0][FIX] hr_utilization_report & hr_utilization_analysis: _get_*_days_data => _get_*_days_data_batch
  hr_utilization_analysis/report/hr_utilization_analysis.py
  hr_utilization_report/report/hr_utilization_report.py
Labels: bot is merging ⏳

#529 [13.0][MIG] hr_timesheet_role
  hr_timesheet_role/README.rst
  hr_timesheet_role/__init__.py
  hr_timesheet_role/__manifest__.py
  hr_timesheet_role/i18n/de.po
  hr_timesheet_role/i18n/es.po
  hr_timesheet_role/i18n/fr.po
  hr_timesheet_role/i18n/hr_timesheet_role.pot
  hr_timesheet_role/i18n/pt.po
  hr_timesheet_role/models/__init__.py
  hr_timesheet_role/models/account_analytic_line.py
  hr_timesheet_role/models/project_project.py
  hr_timesheet_role/models/res_company.py
  hr_timesheet_role/models/res_config_settings.py
  hr_timesheet_role/readme/CONTRIBUTORS.rst
  hr_timesheet_role/readme/DESCRIPTION.rst
  hr_timesheet_role/report/report_timesheet_templates.xml
  hr_timesheet_role/static/description/icon.png
  hr_timesheet_role/static/description/index.html
  hr_timesheet_role/tests/__init__.py
  hr_timesheet_role/tests/test_hr_timesheet_role.py
  hr_timesheet_role/views/account_analytic_line.xml
  hr_timesheet_role/views/project_portal_templates.xml
  hr_timesheet_role/views/project_project.xml
  hr_timesheet_role/views/project_task.xml
  hr_timesheet_role/views/res_config_settings.xml
  setup/hr_timesheet_role/odoo/addons/hr_timesheet_role
  setup/hr_timesheet_role/setup.py
Labels: bot is merging ⏳

#526 [12.0][IMP] hr_utilization_analysis: support date range for usability
  hr_utilization_analysis/__manifest__.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.py
  hr_utilization_analysis/wizards/hr_utilization_analysis_wizard.xml
Labels: bot is merging ⏳

#532 [12.0][FIX] sale_timesheet_task_exclude self is a recordset
  sale_timesheet_task_exclude/models/project_task.py
Labels: bot is merging ⏳

#533 [13.0][FIX] sale_timesheet_task_exclude self is a recordset
  sale_timesheet_task_exclude/models/project_task.py
Labels: bot is merging ⏳

#534 [15.0][FIX] sale_timesheet_task_exclude self is a recordset
  sale_timesheet_task_exclude/models/project_task.py
Labels: bot is merging ⏳

#535 [14.0][FIX] hr_timesheet_task_stage: Avoid texts on buttons
  hr_timesheet_task_stage/views/account_analytic_line.xml
Labels: approved, bot is merging ⏳

#536 [15.0][FIX] hr_timesheet_task_stage: Avoid texts on buttons
  hr_timesheet_task_stage/views/account_analytic_line.xml
Labels: approved, bot is merging ⏳
