Repository OCA/timesheet, pull requests merged in 2023-12, with the labels that each got.

#623 [14.0][UPD] Updated from template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  hr_timesheet_sheet/security/hr_timesheet_sheet_security.xml
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
  hr_timesheet_time_type/views/project_time_type_view.xml
Labels: bot is merging ⏳

#595 [14.0][IMP] hr_timesheet_sheet
  hr_timesheet_sheet/README.rst
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/models/res_company.py
  hr_timesheet_sheet/models/res_config.py
  hr_timesheet_sheet/readme/CONFIGURE.rst
  hr_timesheet_sheet/static/description/index.html
  hr_timesheet_sheet/tests/__init__.py
  hr_timesheet_sheet/tests/test_hr_timesheet_reviewer_no_email.py
  hr_timesheet_sheet/views/res_config_settings_views.xml
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#624 [14.0][FIX] sale_timesheet_order_line_no_update: dumps domain
  sale_timesheet_order_line_no_update/README.rst
  sale_timesheet_order_line_no_update/__manifest__.py
  sale_timesheet_order_line_no_update/models/account_analytic_line.py
  sale_timesheet_order_line_no_update/models/project.py
  sale_timesheet_order_line_no_update/models/res_config_settings.py
  sale_timesheet_order_line_no_update/static/description/index.html
  sale_timesheet_order_line_no_update/tests/test_sale_timesheet_order_line_no_update.py
Labels: approved, bot is merging ⏳
