Repository OCA/timesheet, pull requests merged in 2024-03, with the labels that each got.

#634 [16.0][MIG]hr_timesheet_sheet_autodraft: Migration to V16
  hr_timesheet_sheet_autodraft/README.rst
  hr_timesheet_sheet_autodraft/__init__.py
  hr_timesheet_sheet_autodraft/__manifest__.py
  hr_timesheet_sheet_autodraft/i18n/hr_timesheet_sheet_autodraft.pot
  hr_timesheet_sheet_autodraft/i18n/it.po
  hr_timesheet_sheet_autodraft/i18n/nl.po
  hr_timesheet_sheet_autodraft/models/__init__.py
  hr_timesheet_sheet_autodraft/models/account_analytic_line.py
  hr_timesheet_sheet_autodraft/models/res_company.py
  hr_timesheet_sheet_autodraft/models/res_config.py
  hr_timesheet_sheet_autodraft/readme/CONFIGURE.rst
  hr_timesheet_sheet_autodraft/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_autodraft/readme/DESCRIPTION.rst
  hr_timesheet_sheet_autodraft/static/description/icon.png
  hr_timesheet_sheet_autodraft/static/description/index.html
  hr_timesheet_sheet_autodraft/tests/__init__.py
  hr_timesheet_sheet_autodraft/tests/test_hr_timesheet_sheet_autodraft.py
  hr_timesheet_sheet_autodraft/views/account_analytic_line.xml
  hr_timesheet_sheet_autodraft/views/res_config_settings.xml
  setup/hr_timesheet_sheet_autodraft/odoo/addons/hr_timesheet_sheet_autodraft
  setup/hr_timesheet_sheet_autodraft/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#633 [15.0][MIG]hr_timesheet_sheet_autodraft
  hr_timesheet_sheet_autodraft/README.rst
  hr_timesheet_sheet_autodraft/__init__.py
  hr_timesheet_sheet_autodraft/__manifest__.py
  hr_timesheet_sheet_autodraft/i18n/hr_timesheet_sheet_autodraft.pot
  hr_timesheet_sheet_autodraft/i18n/it.po
  hr_timesheet_sheet_autodraft/i18n/nl.po
  hr_timesheet_sheet_autodraft/models/__init__.py
  hr_timesheet_sheet_autodraft/models/account_analytic_line.py
  hr_timesheet_sheet_autodraft/models/res_company.py
  hr_timesheet_sheet_autodraft/models/res_config.py
  hr_timesheet_sheet_autodraft/readme/CONFIGURE.rst
  hr_timesheet_sheet_autodraft/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_autodraft/readme/DESCRIPTION.rst
  hr_timesheet_sheet_autodraft/static/description/icon.png
  hr_timesheet_sheet_autodraft/static/description/index.html
  hr_timesheet_sheet_autodraft/tests/__init__.py
  hr_timesheet_sheet_autodraft/tests/test_hr_timesheet_sheet_autodraft.py
  hr_timesheet_sheet_autodraft/views/account_analytic_line.xml
  hr_timesheet_sheet_autodraft/views/res_config_settings.xml
  setup/hr_timesheet_sheet_autodraft/odoo/addons/hr_timesheet_sheet_autodraft
  setup/hr_timesheet_sheet_autodraft/setup.py
Labels: approved, bot is merging ⏳

#640 [17.0][MIG] hr_timesheet_task_required
  hr_timesheet_task_required/README.rst
  hr_timesheet_task_required/__init__.py
  hr_timesheet_task_required/__manifest__.py
  hr_timesheet_task_required/i18n/de.po
  hr_timesheet_task_required/i18n/es.po
  hr_timesheet_task_required/i18n/fr.po
  hr_timesheet_task_required/i18n/fr_FR.po
  hr_timesheet_task_required/i18n/hr_timesheet_task_required.pot
  hr_timesheet_task_required/i18n/it.po
  hr_timesheet_task_required/i18n/nl.po
  hr_timesheet_task_required/i18n/nl_NL.po
  hr_timesheet_task_required/i18n/pt_BR.po
  hr_timesheet_task_required/models/__init__.py
  hr_timesheet_task_required/models/account_analytic_line.py
  hr_timesheet_task_required/models/project_project.py
  hr_timesheet_task_required/models/res_company.py
  hr_timesheet_task_required/models/res_config_settings.py
  hr_timesheet_task_required/pyproject.toml
  hr_timesheet_task_required/readme/CONFIGURE.md
  hr_timesheet_task_required/readme/CONTRIBUTORS.md
  hr_timesheet_task_required/readme/DESCRIPTION.md
  hr_timesheet_task_required/static/description/icon.png
  hr_timesheet_task_required/static/description/index.html
  hr_timesheet_task_required/tests/__init__.py
  hr_timesheet_task_required/tests/test_hr_timesheet_task_required.py
  hr_timesheet_task_required/views/account_analytic_line.xml
  hr_timesheet_task_required/views/project_project.xml
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#632 [17.0][MIG] hr_timesheet_begin_end: Migration to 17.0
  hr_timesheet_begin_end/README.rst
  hr_timesheet_begin_end/__init__.py
  hr_timesheet_begin_end/__manifest__.py
  hr_timesheet_begin_end/i18n/ca.po
  hr_timesheet_begin_end/i18n/cs_CZ.po
  hr_timesheet_begin_end/i18n/de.po
  hr_timesheet_begin_end/i18n/es.po
  hr_timesheet_begin_end/i18n/fr.po
  hr_timesheet_begin_end/i18n/hr_timesheet_begin_end.pot
  hr_timesheet_begin_end/i18n/it.po
  hr_timesheet_begin_end/i18n/nl_NL.po
  hr_timesheet_begin_end/i18n/pt_BR.po
  hr_timesheet_begin_end/i18n/sv.po
  hr_timesheet_begin_end/i18n/sv_SE.po
  hr_timesheet_begin_end/models/__init__.py
  hr_timesheet_begin_end/models/account_analytic_line.py
  hr_timesheet_begin_end/pyproject.toml
  hr_timesheet_begin_end/readme/CONTRIBUTORS.md
  hr_timesheet_begin_end/readme/DESCRIPTION.md
  hr_timesheet_begin_end/static/description/icon.png
  hr_timesheet_begin_end/static/description/index.html
  hr_timesheet_begin_end/tests/__init__.py
  hr_timesheet_begin_end/tests/test_timesheet_begin_end.py
  hr_timesheet_begin_end/views/hr_analytic_timesheet.xml
  hr_timesheet_begin_end/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#628 [14.0] [MIG] hr_timesheet_sheet_no_create: Migration to 14.0
  hr_timesheet_sheet_no_create/README.rst
  hr_timesheet_sheet_no_create/__init__.py
  hr_timesheet_sheet_no_create/__manifest__.py
  hr_timesheet_sheet_no_create/i18n/es.po
  hr_timesheet_sheet_no_create/i18n/hr_timesheet_sheet_no_create.pot
  hr_timesheet_sheet_no_create/i18n/it.po
  hr_timesheet_sheet_no_create/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_no_create/readme/DESCRIPTION.rst
  hr_timesheet_sheet_no_create/static/description/icon.png
  hr_timesheet_sheet_no_create/static/description/index.html
  hr_timesheet_sheet_no_create/views/hr_timesheet_sheet.xml
  setup/hr_timesheet_sheet_no_create/odoo/addons/hr_timesheet_sheet_no_create
  setup/hr_timesheet_sheet_no_create/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#636 [15.0][MIG] hr_timesheet_sheet_no_create: Migration to 15.0
  hr_timesheet_sheet_no_create/README.rst
  hr_timesheet_sheet_no_create/__init__.py
  hr_timesheet_sheet_no_create/__manifest__.py
  hr_timesheet_sheet_no_create/i18n/es.po
  hr_timesheet_sheet_no_create/i18n/hr_timesheet_sheet_no_create.pot
  hr_timesheet_sheet_no_create/i18n/it.po
  hr_timesheet_sheet_no_create/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_no_create/readme/DESCRIPTION.rst
  hr_timesheet_sheet_no_create/static/description/icon.png
  hr_timesheet_sheet_no_create/static/description/index.html
  hr_timesheet_sheet_no_create/views/hr_timesheet_sheet.xml
  setup/hr_timesheet_sheet_no_create/odoo/addons/hr_timesheet_sheet_no_create
  setup/hr_timesheet_sheet_no_create/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#646 [17.0][FIX] hr_timesheet_task_required: typo
  hr_timesheet_task_required/views/res_config_settings.xml
Labels: bot is merging ⏳

#604 [16.0][MIG] sale_timesheet_rounded: Migration to 16.0
  .copier-answers.yml
  .github/workflows/test.yml
  sale_timesheet_rounded/README.rst
  sale_timesheet_rounded/__init__.py
  sale_timesheet_rounded/__manifest__.py
  sale_timesheet_rounded/hooks.py
  sale_timesheet_rounded/i18n/de.po
  sale_timesheet_rounded/i18n/es.po
  sale_timesheet_rounded/i18n/it.po
  sale_timesheet_rounded/i18n/nl.po
  sale_timesheet_rounded/i18n/sale_timesheet_rounded.pot
  sale_timesheet_rounded/models/__init__.py
  sale_timesheet_rounded/models/account_analytic_line.py
  sale_timesheet_rounded/models/account_move.py
  sale_timesheet_rounded/models/project_project.py
  sale_timesheet_rounded/models/sale.py
  sale_timesheet_rounded/readme/CONFIGURE.rst
  sale_timesheet_rounded/readme/CONTRIBUTORS.rst
  sale_timesheet_rounded/readme/CREDITS.rst
  sale_timesheet_rounded/readme/DESCRIPTION.rst
  sale_timesheet_rounded/readme/ROADMAP.rst
  sale_timesheet_rounded/static/description/icon.png
  sale_timesheet_rounded/static/description/index.html
  sale_timesheet_rounded/tests/__init__.py
  sale_timesheet_rounded/tests/test_rounded.py
  sale_timesheet_rounded/views/account_analytic_line.xml
  sale_timesheet_rounded/views/project_project.xml
  sale_timesheet_rounded/views/project_task.xml
  sale_timesheet_rounded/wizard/__init__.py
  sale_timesheet_rounded/wizard/sale_make_invoice_advance.py
  setup/sale_timesheet_rounded/odoo/addons/sale_timesheet_rounded
  setup/sale_timesheet_rounded/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#648 [16.0][FIX] hr_timesheet_sheet: permissions on access to menus
  hr_timesheet_sheet/i18n/es.po
  hr_timesheet_sheet/i18n/hr_timesheet_sheet.pot
  hr_timesheet_sheet/views/account_analytic_line_views.xml
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#649 [14.0][FIX] hr_utilization_report: missing _description
  hr_utilization_report/report/hr_utilization_report.py
Labels: bot is merging ⏳

#597 [14.0][IMP] hr_timesheet_purchase_order: create PO automatically
  hr_timesheet_purchase_order/__manifest__.py
  hr_timesheet_purchase_order/data/hr_timesheet_cron.xml
  hr_timesheet_purchase_order/data/ir_actions_server.xml
  hr_timesheet_purchase_order/models/__init__.py
  hr_timesheet_purchase_order/models/consts.py
  hr_timesheet_purchase_order/models/hr_employee_base.py
  hr_timesheet_purchase_order/models/hr_timesheet_recurrence.py
  hr_timesheet_purchase_order/models/hr_timesheet_sheet.py
  hr_timesheet_purchase_order/models/purchase_order.py
  hr_timesheet_purchase_order/models/res_company.py
  hr_timesheet_purchase_order/models/res_config_settings.py
  hr_timesheet_purchase_order/models/res_partner.py
  hr_timesheet_purchase_order/readme/CONFIGURE.rst
  hr_timesheet_purchase_order/readme/DESCRIPTION.rst
  hr_timesheet_purchase_order/readme/USAGE.rst
  hr_timesheet_purchase_order/security/ir.model.access.csv
  hr_timesheet_purchase_order/tests/__init__.py
  hr_timesheet_purchase_order/tests/common_po_recurrence.py
  hr_timesheet_purchase_order/tests/test_create_not_product.py
  hr_timesheet_purchase_order/tests/test_create_timesheet_po_recurrence.py
  hr_timesheet_purchase_order/tests/test_create_timesheet_purchase_order.py
  hr_timesheet_purchase_order/views/hr_timesheet_sheet_view.xml
  hr_timesheet_purchase_order/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#651 [14.0][FIX] sale_timesheet_order_line_no_update
  sale_timesheet_order_line_no_update/views/project.xml
Labels: bot is merging ⏳

#639 [17.0][MIG] sale_timesheet_line_exclude
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__init__.py
  sale_timesheet_line_exclude/__manifest__.py
  sale_timesheet_line_exclude/i18n/de.po
  sale_timesheet_line_exclude/i18n/es.po
  sale_timesheet_line_exclude/i18n/fr.po
  sale_timesheet_line_exclude/i18n/it.po
  sale_timesheet_line_exclude/i18n/pt_BR.po
  sale_timesheet_line_exclude/i18n/sale_timesheet_line_exclude.pot
  sale_timesheet_line_exclude/models/__init__.py
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/pyproject.toml
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.md
  sale_timesheet_line_exclude/readme/DESCRIPTION.md
  sale_timesheet_line_exclude/readme/USAGE.md
  sale_timesheet_line_exclude/static/description/icon.png
  sale_timesheet_line_exclude/static/description/index.html
  sale_timesheet_line_exclude/tests/__init__.py
  sale_timesheet_line_exclude/tests/test_sale_timesheet_line_exclude.py
  sale_timesheet_line_exclude/views/account_analytic_line.xml
  sale_timesheet_line_exclude/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#655 [14.0][FIX] hr_timesheet_sheet: Re-use original arguments
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: bot is merging ⏳

#662 [14.0][FIX] hr_timesheet_sheet: Don't merge timesheets during onchange
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
Labels: approved, bot is merging ⏳
