Repository OCA/timesheet, pull requests merged in 2024-05, with the labels that each got.

#672 [16.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: help wanted, needs review, bot is merging ⏳

#657 [16.0][IMP] hr_timesheet_begin_end: Change line overlap domain from looking for user to employee
  hr_timesheet_begin_end/models/account_analytic_line.py
Labels: approved, ready to merge, bot is merging ⏳

#669 [16.0][MIG] hr_timesheet_sheet_attendance
  hr_timesheet_sheet_attendance/README.rst
  hr_timesheet_sheet_attendance/__init__.py
  hr_timesheet_sheet_attendance/__manifest__.py
  hr_timesheet_sheet_attendance/i18n/es.po
  hr_timesheet_sheet_attendance/i18n/hr_timesheet_sheet_attendance.pot
  hr_timesheet_sheet_attendance/i18n/it.po
  hr_timesheet_sheet_attendance/i18n/pt_BR.po
  hr_timesheet_sheet_attendance/models/__init__.py
  hr_timesheet_sheet_attendance/models/hr_attendance.py
  hr_timesheet_sheet_attendance/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_attendance/readme/DESCRIPTION.rst
  hr_timesheet_sheet_attendance/readme/INSTALL.rst
  hr_timesheet_sheet_attendance/readme/ROADMAP.rst
  hr_timesheet_sheet_attendance/readme/USAGE.rst
  hr_timesheet_sheet_attendance/static/description/icon.png
  hr_timesheet_sheet_attendance/static/description/index.html
  hr_timesheet_sheet_attendance/tests/__init__.py
  hr_timesheet_sheet_attendance/tests/hr_timesheet_sheet_test_cases.py
  hr_timesheet_sheet_attendance/tests/test_hr_attendance.py
  hr_timesheet_sheet_attendance/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/views/hr_attendance_view.xml
  hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
  setup/hr_timesheet_sheet_attendance/odoo/addons/hr_timesheet_sheet_attendance
  setup/hr_timesheet_sheet_attendance/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#654 [15.0][IMP] hr_timesheet_sheet: add My Current Timesheet menu.
  hr_timesheet_sheet/__init__.py
  hr_timesheet_sheet/security/ir.model.access.csv
  hr_timesheet_sheet/views/hr_timesheet_sheet_views.xml
  hr_timesheet_sheet/wizard/__init__.py
  hr_timesheet_sheet/wizard/hr_timesheet_current.py
Labels: approved, bot is merging ⏳

#671 [ADD] sale_timesheet_invoice_link: Link invoices with timesheet lines
  sale_timesheet_invoice_link/README.rst
  sale_timesheet_invoice_link/__init__.py
  sale_timesheet_invoice_link/__manifest__.py
  sale_timesheet_invoice_link/readme/CONFIGURE.md
  sale_timesheet_invoice_link/readme/CONTEXT.md
  sale_timesheet_invoice_link/readme/CONTRIBUTORS.md
  sale_timesheet_invoice_link/readme/DESCRIPTION.md
  sale_timesheet_invoice_link/readme/ROADMAP.md
  sale_timesheet_invoice_link/readme/USAGE.md
  sale_timesheet_invoice_link/static/description/icon.png
  sale_timesheet_invoice_link/static/description/index.html
  sale_timesheet_invoice_link/views/account_analytic_line_view.xml
  setup/sale_timesheet_invoice_link/odoo/addons/sale_timesheet_invoice_link
  setup/sale_timesheet_invoice_link/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#677 [17.0][IMP] sale_timesheet_line_exclude: add exclude_from_sale_order to form
  sale_timesheet_line_exclude/views/account_analytic_line.xml
Labels: bot is merging ⏳

#679 [14.0][FIX] hr_timesheet_report: lost i18n strings
  hr_timesheet_report/report/hr_timesheet_report.py
Labels: approved, bot is merging ⏳

#680 [14.0][FIX] hr_utilization_report: lost i18n strings
  hr_utilization_report/report/hr_utilization_report.py
Labels: approved, bot is merging ⏳

#678 [16.0] [mig] hr_timesheet_sheet_policy_department_manager
  hr_timesheet_sheet_policy_department_manager/README.rst
  hr_timesheet_sheet_policy_department_manager/__init__.py
  hr_timesheet_sheet_policy_department_manager/__manifest__.py
  hr_timesheet_sheet_policy_department_manager/i18n/es.po
  hr_timesheet_sheet_policy_department_manager/i18n/fr.po
  hr_timesheet_sheet_policy_department_manager/i18n/hr_timesheet_sheet_policy_department_manager.pot
  hr_timesheet_sheet_policy_department_manager/i18n/it.po
  hr_timesheet_sheet_policy_department_manager/models/__init__.py
  hr_timesheet_sheet_policy_department_manager/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_policy_department_manager/models/res_company.py
  hr_timesheet_sheet_policy_department_manager/readme/CONFIGURE.rst
  hr_timesheet_sheet_policy_department_manager/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_policy_department_manager/readme/DESCRIPTION.rst
  hr_timesheet_sheet_policy_department_manager/static/description/icon.png
  hr_timesheet_sheet_policy_department_manager/static/description/index.html
  hr_timesheet_sheet_policy_department_manager/tests/__init__.py
  hr_timesheet_sheet_policy_department_manager/tests/test_hr_timesheet_sheet_policy_department_manager.py
  hr_timesheet_sheet_policy_department_manager/views/hr_timesheet_sheet.xml
  setup/hr_timesheet_sheet_policy_department_manager/odoo/addons/hr_timesheet_sheet_policy_department_manager
  setup/hr_timesheet_sheet_policy_department_manager/setup.py
Labels: approved, ready to merge, bot is merging ⏳
