Repository OCA/timesheet, pull requests merged in 2024-04, with the labels that each got.

#666 [14.0][FIX] sale_timesheet_order_line_no_update: create from kanban
  sale_timesheet_order_line_no_update/views/project.xml
Labels: bot is merging ⏳

#635 [ADD] hr_employee_cost_history: Updates employee hourly cost ret…
  hr_employee_cost_history/README.rst
  hr_employee_cost_history/__init__.py
  hr_employee_cost_history/__manifest__.py
  hr_employee_cost_history/i18n/es.po
  hr_employee_cost_history/models/__init__.py
  hr_employee_cost_history/models/hr_employee.py
  hr_employee_cost_history/models/hr_employee_timesheet_cost_history.py
  hr_employee_cost_history/readme/CONTRIBUTORS.md
  hr_employee_cost_history/readme/DESCRIPTION.md
  hr_employee_cost_history/readme/USAGE.md
  hr_employee_cost_history/security/ir.model.access.csv
  hr_employee_cost_history/static/description/icon.png
  hr_employee_cost_history/static/description/index.html
  hr_employee_cost_history/tests/__init__.py
  hr_employee_cost_history/tests/test_hr_timesheet.py
  hr_employee_cost_history/views/hr_employee_timesheet_cost_history_views.xml
  hr_employee_cost_history/views/hr_employee_views.xml
  hr_employee_cost_history/wizards/__init__.py
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard.py
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard_views.xml
  requirements.txt
  setup/hr_employee_cost_history/odoo/addons/hr_employee_cost_history
  setup/hr_employee_cost_history/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#670 [16.0] MIG hr_employee_cost_history
  hr_employee_cost_history/README.rst
  hr_employee_cost_history/__init__.py
  hr_employee_cost_history/__manifest__.py
  hr_employee_cost_history/i18n/es.po
  hr_employee_cost_history/models/__init__.py
  hr_employee_cost_history/models/hr_employee.py
  hr_employee_cost_history/models/hr_employee_timesheet_cost_history.py
  hr_employee_cost_history/readme/CONTRIBUTORS.md
  hr_employee_cost_history/readme/DESCRIPTION.md
  hr_employee_cost_history/readme/USAGE.md
  hr_employee_cost_history/security/ir.model.access.csv
  hr_employee_cost_history/static/description/icon.png
  hr_employee_cost_history/static/description/index.html
  hr_employee_cost_history/tests/__init__.py
  hr_employee_cost_history/tests/test_hr_timesheet.py
  hr_employee_cost_history/views/hr_employee_timesheet_cost_history_views.xml
  hr_employee_cost_history/views/hr_employee_views.xml
  hr_employee_cost_history/wizards/__init__.py
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard.py
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard_views.xml
  requirements.txt
  setup/hr_employee_cost_history/odoo/addons/hr_employee_cost_history
  setup/hr_employee_cost_history/setup.py
Labels: bot is merging ⏳

#605 [15.0][MIG] hr_timesheet_sheet_attendance
  hr_timesheet_sheet_attendance/README.rst
  hr_timesheet_sheet_attendance/__init__.py
  hr_timesheet_sheet_attendance/__manifest__.py
  hr_timesheet_sheet_attendance/i18n/hr_timesheet_sheet_attendance.pot
  hr_timesheet_sheet_attendance/i18n/it.po
  hr_timesheet_sheet_attendance/i18n/pt_BR.po
  hr_timesheet_sheet_attendance/models/__init__.py
  hr_timesheet_sheet_attendance/models/hr_attendance.py
  hr_timesheet_sheet_attendance/models/hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/readme/CONTRIBUTORS.rst
  hr_timesheet_sheet_attendance/readme/DESCRIPTION.rst
  hr_timesheet_sheet_attendance/readme/INSTALL.rst
  hr_timesheet_sheet_attendance/readme/ROADMAP.rst
  hr_timesheet_sheet_attendance/readme/USAGE.rst
  hr_timesheet_sheet_attendance/static/description/icon.png
  hr_timesheet_sheet_attendance/static/description/index.html
  hr_timesheet_sheet_attendance/tests/__init__.py
  hr_timesheet_sheet_attendance/tests/hr_timesheet_sheet_test_cases.py
  hr_timesheet_sheet_attendance/tests/test_hr_attendance.py
  hr_timesheet_sheet_attendance/tests/test_hr_timesheet_sheet.py
  hr_timesheet_sheet_attendance/views/hr_attendance_view.xml
  hr_timesheet_sheet_attendance/views/hr_timesheet_sheet_view.xml
  setup/hr_timesheet_sheet_attendance/odoo/addons/hr_timesheet_sheet_attendance
  setup/hr_timesheet_sheet_attendance/setup.py
Labels: approved, bot is merging ⏳, stale
