Repository OCA/timesheet, pull requests merged in 2024-09, with the labels that each got.

#664 [16.0][FIX] hr_timesheet_sheet: Don't merge timesheets during onchange
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
  hr_timesheet_sheet/tests/test_hr_timesheet_sheet.py
Labels: bot is merging ⏳, stale

#712 [16.0][FIX] hr_timesheet_sheet: deal with time off line
  hr_timesheet_sheet/models/hr_timesheet_sheet.py
Labels: approved, ready to merge, bot is merging ⏳

#709 [14.0][ADD] hr_timesheet_predefined_description: Add predefined descriptions for timesheets
  hr_timesheet_predefined_description/README.rst
  hr_timesheet_predefined_description/__init__.py
  hr_timesheet_predefined_description/__manifest__.py
  hr_timesheet_predefined_description/demo/hr_timesheet_predefined_description_demo.xml
  hr_timesheet_predefined_description/models/__init__.py
  hr_timesheet_predefined_description/models/account_analytic_line.py
  hr_timesheet_predefined_description/models/hr_timesheet_predefined_description.py
  hr_timesheet_predefined_description/readme/CONFIGURE.rst
  hr_timesheet_predefined_description/readme/CONTRIBUTORS.rst
  hr_timesheet_predefined_description/readme/DESCRIPTION.rst
  hr_timesheet_predefined_description/readme/USAGE.rst
  hr_timesheet_predefined_description/security/ir.model.access.csv
  hr_timesheet_predefined_description/security/timesheet_predefined_description_security.xml
  hr_timesheet_predefined_description/static/description/icon.png
  hr_timesheet_predefined_description/static/description/index.html
  hr_timesheet_predefined_description/tests/__init__.py
  hr_timesheet_predefined_description/tests/test_account_analytic_line.py
  hr_timesheet_predefined_description/views/account_analytic_line_views.xml
  hr_timesheet_predefined_description/views/timesheet_predefined_description_views.xml
  setup/hr_timesheet_predefined_description/odoo/addons/hr_timesheet_predefined_description
  setup/hr_timesheet_predefined_description/setup.py
Labels: bot is merging ⏳
