Repository OCA/timesheet, pull requests merged in 2024-10, with the labels that each got.

#707 [16.0][IMP] sale_timesheet_line_exclude: add security group
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__manifest__.py
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/readme/USAGE.rst
  sale_timesheet_line_exclude/security/exclude_from_sale_order.xml
  sale_timesheet_line_exclude/static/description/index.html
Labels: needs review, approved, ready to merge, bot is merging ⏳

#718 [FIX] sale_timesheet_line_exclude: recompute so line when changing exclude flag
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/tests/test_sale_timesheet_line_exclude.py
Labels: bot is merging ⏳

#708 [16.0][ADD] sale_timesheet_timeline: Dates planning in sales order lines
  sale_timesheet_timeline/README.rst
  sale_timesheet_timeline/__init__.py
  sale_timesheet_timeline/__manifest__.py
  sale_timesheet_timeline/i18n/es.po
  sale_timesheet_timeline/i18n/sale_timesheet_timeline.pot
  sale_timesheet_timeline/models/__init__.py
  sale_timesheet_timeline/models/sale_order.py
  sale_timesheet_timeline/readme/CONTRIBUTORS.rst
  sale_timesheet_timeline/readme/DESCRIPTION.rst
  sale_timesheet_timeline/readme/ROADMAP.rst
  sale_timesheet_timeline/readme/USAGE.rst
  sale_timesheet_timeline/static/description/index.html
  sale_timesheet_timeline/tests/__init__.py
  sale_timesheet_timeline/tests/test_sale_timesheet_timeline.py
  sale_timesheet_timeline/views/sale_order_views.xml
  sale_timesheet_timeline/views/sale_portal_templates.xml
  setup/sale_timesheet_timeline/odoo/addons/sale_timesheet_timeline
  setup/sale_timesheet_timeline/setup.py
Labels: approved, ready to merge, bot is merging ⏳
