Repository OCA/timesheet, pull requests merged in 2025-05, with the labels that each got.

#751 [16.0][IMP] hr_timesheet_time_type: add the active field to be able t…
  hr_timesheet_time_type/models/project_time_type.py
  hr_timesheet_time_type/views/project_time_type_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#779 [17.0][FIX] sale_timesheet_line_exclude: Fixed an error when entering timesheet reports
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__init__.py
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.md
  sale_timesheet_line_exclude/report/__init__.py
  sale_timesheet_line_exclude/report/timesheets_analysis_report.py
  sale_timesheet_line_exclude/static/description/index.html
Labels: approved, bot is merging ⏳

#769 [18.0][MIG] sale_timesheet_line_exclude: Migration to 18.0
  sale_timesheet_line_exclude/README.rst
  sale_timesheet_line_exclude/__init__.py
  sale_timesheet_line_exclude/__manifest__.py
  sale_timesheet_line_exclude/i18n/de.po
  sale_timesheet_line_exclude/i18n/es.po
  sale_timesheet_line_exclude/i18n/fr.po
  sale_timesheet_line_exclude/i18n/it.po
  sale_timesheet_line_exclude/i18n/pt_BR.po
  sale_timesheet_line_exclude/i18n/sale_timesheet_line_exclude.pot
  sale_timesheet_line_exclude/models/__init__.py
  sale_timesheet_line_exclude/models/account_analytic_line.py
  sale_timesheet_line_exclude/pyproject.toml
  sale_timesheet_line_exclude/readme/CONTRIBUTORS.md
  sale_timesheet_line_exclude/readme/DESCRIPTION.md
  sale_timesheet_line_exclude/readme/USAGE.md
  sale_timesheet_line_exclude/security/exclude_from_sale_order.xml
  sale_timesheet_line_exclude/static/description/icon.png
  sale_timesheet_line_exclude/static/description/index.html
  sale_timesheet_line_exclude/tests/__init__.py
  sale_timesheet_line_exclude/tests/test_sale_timesheet_line_exclude.py
  sale_timesheet_line_exclude/views/account_analytic_line.xml
  sale_timesheet_line_exclude/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#737 [17.0][MIG] project_task_analytic_propagation: Migration to 17.0
  project_task_analytic_propagation/README.rst
  project_task_analytic_propagation/__init__.py
  project_task_analytic_propagation/__manifest__.py
  project_task_analytic_propagation/i18n/it.po
  project_task_analytic_propagation/i18n/project_task_analytic_propagation.pot
  project_task_analytic_propagation/i18n/pt_BR.po
  project_task_analytic_propagation/models/__init__.py
  project_task_analytic_propagation/models/account_analytic_line.py
  project_task_analytic_propagation/pyproject.toml
  project_task_analytic_propagation/readme/CONTRIBUTORS.md
  project_task_analytic_propagation/readme/DESCRIPTION.md
  project_task_analytic_propagation/readme/USAGE.md
  project_task_analytic_propagation/static/description/icon.png
  project_task_analytic_propagation/static/description/index.html
  project_task_analytic_propagation/tests/__init__.py
  project_task_analytic_propagation/tests/test_hr_timesheet.py
Labels: approved, ready to merge, bot is merging ⏳

#774 [17.0][UPD] hr_timesheet_begin_end: add a hint for project_timesheet_time_control
  hr_timesheet_begin_end/README.rst
  hr_timesheet_begin_end/readme/DESCRIPTION.md
  hr_timesheet_begin_end/static/description/index.html
Labels: approved, bot is merging ⏳

#760 [17.0][MIG] hr_timesheet_sheet_autodraft: Migration to 17.0
  hr_timesheet_sheet/views/res_config_settings_views.xml
  hr_timesheet_sheet_autodraft/README.rst
  hr_timesheet_sheet_autodraft/__init__.py
  hr_timesheet_sheet_autodraft/__manifest__.py
  hr_timesheet_sheet_autodraft/i18n/hr_timesheet_sheet_autodraft.pot
  hr_timesheet_sheet_autodraft/i18n/it.po
  hr_timesheet_sheet_autodraft/i18n/nl.po
  hr_timesheet_sheet_autodraft/models/__init__.py
  hr_timesheet_sheet_autodraft/models/account_analytic_line.py
  hr_timesheet_sheet_autodraft/models/res_company.py
  hr_timesheet_sheet_autodraft/models/res_config.py
  hr_timesheet_sheet_autodraft/pyproject.toml
  hr_timesheet_sheet_autodraft/readme/CONFIGURE.md
  hr_timesheet_sheet_autodraft/readme/CONTRIBUTORS.md
  hr_timesheet_sheet_autodraft/readme/DESCRIPTION.md
  hr_timesheet_sheet_autodraft/static/description/icon.png
  hr_timesheet_sheet_autodraft/static/description/index.html
  hr_timesheet_sheet_autodraft/tests/__init__.py
  hr_timesheet_sheet_autodraft/tests/test_hr_timesheet_sheet_autodraft.py
  hr_timesheet_sheet_autodraft/views/account_analytic_line.xml
  hr_timesheet_sheet_autodraft/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#753 [18.0][MIG] hr_timesheet_editable_top: Migration to 18.0
  hr_timesheet_editable_top/README.rst
  hr_timesheet_editable_top/__init__.py
  hr_timesheet_editable_top/__manifest__.py
  hr_timesheet_editable_top/i18n/hr_timesheet_editable_top.pot
  hr_timesheet_editable_top/i18n/it.po
  hr_timesheet_editable_top/pyproject.toml
  hr_timesheet_editable_top/readme/CONTRIBUTORS.md
  hr_timesheet_editable_top/readme/DESCRIPTION.md
  hr_timesheet_editable_top/static/description/icon.png
  hr_timesheet_editable_top/static/description/index.html
  hr_timesheet_editable_top/views/hr_analytic_timesheet.xml
Labels: approved, bot is merging ⏳

#778 [17.0][ADD] hr_timesheet_unusual_days: display unusal days in calendar with a different background color
  hr_timesheet_unusual_days/README.rst
  hr_timesheet_unusual_days/__init__.py
  hr_timesheet_unusual_days/__manifest__.py
  hr_timesheet_unusual_days/models/__init__.py
  hr_timesheet_unusual_days/models/account_analytic_line.py
  hr_timesheet_unusual_days/pyproject.toml
  hr_timesheet_unusual_days/readme/CONTRIBUTORS.md
  hr_timesheet_unusual_days/readme/DESCRIPTION.md
  hr_timesheet_unusual_days/static/description/calendar.drawio.png
  hr_timesheet_unusual_days/static/description/icon.png
  hr_timesheet_unusual_days/static/description/index.html
  hr_timesheet_unusual_days/tests/__init__.py
  hr_timesheet_unusual_days/tests/test_account_analytic_line.py
  hr_timesheet_unusual_days/views/hr_timesheet_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#781 [18.0][PORT] hr_timesheet_begin_end: add a hint for project_timesheet_time_control
  hr_timesheet_begin_end/README.rst
  hr_timesheet_begin_end/readme/DESCRIPTION.md
  hr_timesheet_begin_end/static/description/index.html
Labels: bot is merging ⏳

#757 [16.0][MIG] hr_timesheet_time_restriction: Migration to 16.0
  hr_timesheet_time_restriction/README.rst
  hr_timesheet_time_restriction/__init__.py
  hr_timesheet_time_restriction/__manifest__.py
  hr_timesheet_time_restriction/i18n/hr_timesheet_time_restriction.pot
  hr_timesheet_time_restriction/i18n/it.po
  hr_timesheet_time_restriction/models/__init__.py
  hr_timesheet_time_restriction/models/account_analytic_line.py
  hr_timesheet_time_restriction/models/project_project.py
  hr_timesheet_time_restriction/models/res_config_settings.py
  hr_timesheet_time_restriction/readme/CONFIGURE.rst
  hr_timesheet_time_restriction/readme/CONTRIBUTORS.rst
  hr_timesheet_time_restriction/readme/CREDITS.rst
  hr_timesheet_time_restriction/readme/DESCRIPTION.rst
  hr_timesheet_time_restriction/security/res_groups.xml
  hr_timesheet_time_restriction/static/description/icon.png
  hr_timesheet_time_restriction/static/description/index.html
  hr_timesheet_time_restriction/tests/__init__.py
  hr_timesheet_time_restriction/tests/test_disabled_hr_timesheet_time_restriction.py
  hr_timesheet_time_restriction/tests/test_enabled_hr_timesheet_time_restriction.py
  hr_timesheet_time_restriction/views/project_project_view.xml
  hr_timesheet_time_restriction/views/res_config_settings_view.xml
  setup/hr_timesheet_time_restriction/odoo/addons/hr_timesheet_time_restriction
  setup/hr_timesheet_time_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#742 [16.0][IMP] hr_timesheet_name_customer: Show "Description Customer" in portal
  hr_timesheet_name_customer/README.rst
  hr_timesheet_name_customer/__init__.py
  hr_timesheet_name_customer/__manifest__.py
  hr_timesheet_name_customer/readme/CONFIGURE.rst
  hr_timesheet_name_customer/readme/CONTEXT.rst
  hr_timesheet_name_customer/readme/DESCRIPTION.rst
  hr_timesheet_name_customer/readme/USAGE.rst
  hr_timesheet_name_customer/static/description/icon.png
  hr_timesheet_name_customer/static/description/index.html
  hr_timesheet_name_customer/views/project_portal_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#735 [IMP] hr_employee_cost_history: add comment field in history line
  hr_employee_cost_history/models/hr_employee_timesheet_cost_history.py
  hr_employee_cost_history/tests/test_hr_timesheet.py
  hr_employee_cost_history/views/hr_employee_timesheet_cost_history_views.xml
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard.py
  hr_employee_cost_history/wizards/hr_employee_timesheet_cost_wizard_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#782 [18.0][MIG] sale_timesheet_timeline: Migration to version 18.0
  sale_timesheet_timeline/README.rst
  sale_timesheet_timeline/__init__.py
  sale_timesheet_timeline/__manifest__.py
  sale_timesheet_timeline/i18n/es.po
  sale_timesheet_timeline/i18n/it.po
  sale_timesheet_timeline/i18n/sale_timesheet_timeline.pot
  sale_timesheet_timeline/models/__init__.py
  sale_timesheet_timeline/models/sale_order.py
  sale_timesheet_timeline/pyproject.toml
  sale_timesheet_timeline/readme/CONTRIBUTORS.md
  sale_timesheet_timeline/readme/DESCRIPTION.md
  sale_timesheet_timeline/readme/ROADMAP.md
  sale_timesheet_timeline/readme/USAGE.md
  sale_timesheet_timeline/static/description/icon.png
  sale_timesheet_timeline/static/description/index.html
  sale_timesheet_timeline/tests/__init__.py
  sale_timesheet_timeline/tests/test_sale_timesheet_timeline.py
  sale_timesheet_timeline/views/sale_order_views.xml
  sale_timesheet_timeline/views/sale_portal_templates.xml
Labels: approved, bot is merging ⏳
