Repository OCA/timesheet, pull requests merged in 2025-04, with the labels that each got.

#758 [16.0][ADD] hr_timesheet_date_order_desc: New module hr_timesheet_dat…
  hr_timesheet_date_order_desc/README.rst
  hr_timesheet_date_order_desc/__init__.py
  hr_timesheet_date_order_desc/__manifest__.py
  hr_timesheet_date_order_desc/readme/CONTRIBUTORS.rst
  hr_timesheet_date_order_desc/readme/DESCRIPTION.rst
  hr_timesheet_date_order_desc/static/description/icon.png
  hr_timesheet_date_order_desc/static/description/index.html
  hr_timesheet_date_order_desc/views/hr_analytic_timesheet.xml
  setup/hr_timesheet_date_order_desc/odoo/addons/hr_timesheet_date_order_desc
  setup/hr_timesheet_date_order_desc/setup.py
Labels: approved, ready to merge

#729 [18.0][MIG] hr_timesheet_begin_end: Migration to 18.0
  hr_timesheet_begin_end/README.rst
  hr_timesheet_begin_end/__init__.py
  hr_timesheet_begin_end/__manifest__.py
  hr_timesheet_begin_end/i18n/ca.po
  hr_timesheet_begin_end/i18n/cs_CZ.po
  hr_timesheet_begin_end/i18n/de.po
  hr_timesheet_begin_end/i18n/es.po
  hr_timesheet_begin_end/i18n/fr.po
  hr_timesheet_begin_end/i18n/hr_timesheet_begin_end.pot
  hr_timesheet_begin_end/i18n/it.po
  hr_timesheet_begin_end/i18n/nl_NL.po
  hr_timesheet_begin_end/i18n/pt_BR.po
  hr_timesheet_begin_end/i18n/sv.po
  hr_timesheet_begin_end/i18n/sv_SE.po
  hr_timesheet_begin_end/models/__init__.py
  hr_timesheet_begin_end/models/account_analytic_line.py
  hr_timesheet_begin_end/pyproject.toml
  hr_timesheet_begin_end/readme/CONTRIBUTORS.md
  hr_timesheet_begin_end/readme/DESCRIPTION.md
  hr_timesheet_begin_end/static/description/icon.png
  hr_timesheet_begin_end/static/description/index.html
  hr_timesheet_begin_end/tests/__init__.py
  hr_timesheet_begin_end/tests/test_timesheet_begin_end.py
  hr_timesheet_begin_end/views/hr_analytic_timesheet.xml
  hr_timesheet_begin_end/views/project_task.xml
Labels: approved, ready to merge, bot is merging ⏳

#762 [17.0][MIG] hr_timesheet_time_type: Migration to 17.0
  hr_timesheet_time_type/README.rst
  hr_timesheet_time_type/__init__.py
  hr_timesheet_time_type/__manifest__.py
  hr_timesheet_time_type/i18n/es.po
  hr_timesheet_time_type/i18n/fr.po
  hr_timesheet_time_type/i18n/hr_timesheet_time_type.pot
  hr_timesheet_time_type/i18n/it.po
  hr_timesheet_time_type/i18n/pt_BR.po
  hr_timesheet_time_type/models/__init__.py
  hr_timesheet_time_type/models/account_analytic_line.py
  hr_timesheet_time_type/models/project_time_type.py
  hr_timesheet_time_type/pyproject.toml
  hr_timesheet_time_type/readme/CONTRIBUTORS.md
  hr_timesheet_time_type/readme/CREDITS.md
  hr_timesheet_time_type/readme/DESCRIPTION.md
  hr_timesheet_time_type/security/ir.model.access.csv
  hr_timesheet_time_type/static/description/icon.png
  hr_timesheet_time_type/static/description/index.html
  hr_timesheet_time_type/views/account_analytic_line_view.xml
  hr_timesheet_time_type/views/project_time_type_view.xml
Labels: approved, bot is merging ⏳

#759 [16.0][ADD] hr_timesheet_type_non_billable: New module hr_timesheet_type_non_billable
  hr_timesheet_type_non_billable/README.rst
  hr_timesheet_type_non_billable/__init__.py
  hr_timesheet_type_non_billable/__manifest__.py
  hr_timesheet_type_non_billable/i18n/ca.po
  hr_timesheet_type_non_billable/i18n/es.po
  hr_timesheet_type_non_billable/models/__init__.py
  hr_timesheet_type_non_billable/models/account_analytic_line.py
  hr_timesheet_type_non_billable/models/project_project.py
  hr_timesheet_type_non_billable/models/project_task.py
  hr_timesheet_type_non_billable/models/project_time_type.py
  hr_timesheet_type_non_billable/readme/CONTRIBUTORS.md
  hr_timesheet_type_non_billable/readme/DESCRIPTION.md
  hr_timesheet_type_non_billable/readme/USAGE.md
  hr_timesheet_type_non_billable/static/description/index.html
  hr_timesheet_type_non_billable/tests/__init__.py
  hr_timesheet_type_non_billable/tests/test_hr_timesheet_type_non_billable.py
  hr_timesheet_type_non_billable/views/project_time_type_view.xml
  setup/hr_timesheet_type_non_billable/odoo/addons/hr_timesheet_type_non_billable
  setup/hr_timesheet_type_non_billable/setup.py
Labels: approved, bot is merging ⏳

#763 [17.0][MIG] hr_timesheet_calendar: Migration to 17.0
  hr_timesheet_calendar/README.rst
  hr_timesheet_calendar/__init__.py
  hr_timesheet_calendar/__manifest__.py
  hr_timesheet_calendar/i18n/hr_timesheet_calendar.pot
  hr_timesheet_calendar/i18n/it.po
  hr_timesheet_calendar/pyproject.toml
  hr_timesheet_calendar/readme/CONTRIBUTORS.md
  hr_timesheet_calendar/readme/DESCRIPTION.md
  hr_timesheet_calendar/static/description/icon.png
  hr_timesheet_calendar/static/description/icon.svg
  hr_timesheet_calendar/static/description/index.html
  hr_timesheet_calendar/views/hr_timesheet_views.xml
Labels: approved, bot is merging ⏳

#765 [17.0][FIX] hr_timesheet_task_stage: Correctly hide is_task_closed column with column_invisible
  hr_timesheet_task_stage/views/account_analytic_line.xml
Labels: approved, bot is merging ⏳

#766 [17.0][FIX] crm_timesheet: Correctly hide lead_id column with column_invisible
  crm_timesheet/views/hr_timesheet_view.xml
Labels: bot is merging ⏳

#767 [18.0][FIX] hr_timesheet_task_stage: Correctly hide is_task_closed column with column_invisible
  hr_timesheet_task_stage/views/account_analytic_line.xml
Labels: bot is merging ⏳

#750 [17.0][MIG] hr_timesheet_editable_top: Migration to 17.0
  hr_timesheet_editable_top/README.rst
  hr_timesheet_editable_top/__init__.py
  hr_timesheet_editable_top/__manifest__.py
  hr_timesheet_editable_top/i18n/hr_timesheet_editable_top.pot
  hr_timesheet_editable_top/i18n/it.po
  hr_timesheet_editable_top/pyproject.toml
  hr_timesheet_editable_top/readme/CONTRIBUTORS.md
  hr_timesheet_editable_top/readme/DESCRIPTION.md
  hr_timesheet_editable_top/static/description/icon.png
  hr_timesheet_editable_top/static/description/index.html
  hr_timesheet_editable_top/views/hr_analytic_timesheet.xml
Labels: approved, ready to merge, bot is merging ⏳

#726 [18.0][MIG] hr_timesheet_task_domain: Migration to 18.0
  hr_timesheet_task_domain/README.rst
  hr_timesheet_task_domain/__init__.py
  hr_timesheet_task_domain/__manifest__.py
  hr_timesheet_task_domain/i18n/de.po
  hr_timesheet_task_domain/i18n/es.po
  hr_timesheet_task_domain/i18n/fr.po
  hr_timesheet_task_domain/i18n/hr_timesheet_task_domain.pot
  hr_timesheet_task_domain/i18n/it.po
  hr_timesheet_task_domain/i18n/pt_BR.po
  hr_timesheet_task_domain/models/__init__.py
  hr_timesheet_task_domain/models/account_analytic_line.py
  hr_timesheet_task_domain/pyproject.toml
  hr_timesheet_task_domain/readme/CONTRIBUTORS.md
  hr_timesheet_task_domain/readme/DESCRIPTION.md
  hr_timesheet_task_domain/static/description/icon.png
  hr_timesheet_task_domain/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#770 [18.0][MIG] hr_timesheet_time_type: Migration to 18.0
  hr_timesheet_time_type/README.rst
  hr_timesheet_time_type/__init__.py
  hr_timesheet_time_type/__manifest__.py
  hr_timesheet_time_type/i18n/es.po
  hr_timesheet_time_type/i18n/fr.po
  hr_timesheet_time_type/i18n/hr_timesheet_time_type.pot
  hr_timesheet_time_type/i18n/it.po
  hr_timesheet_time_type/i18n/pt_BR.po
  hr_timesheet_time_type/models/__init__.py
  hr_timesheet_time_type/models/account_analytic_line.py
  hr_timesheet_time_type/models/project_time_type.py
  hr_timesheet_time_type/pyproject.toml
  hr_timesheet_time_type/readme/CONTRIBUTORS.md
  hr_timesheet_time_type/readme/CREDITS.md
  hr_timesheet_time_type/readme/DESCRIPTION.md
  hr_timesheet_time_type/security/ir.model.access.csv
  hr_timesheet_time_type/static/description/icon.png
  hr_timesheet_time_type/static/description/index.html
  hr_timesheet_time_type/views/account_analytic_line_view.xml
  hr_timesheet_time_type/views/project_time_type_view.xml
Labels: approved, bot is merging ⏳

#768 [17.0][MIG] hr_timesheet_type_non_billable: Migration to 17.0
  hr_timesheet_type_non_billable/README.rst
  hr_timesheet_type_non_billable/__init__.py
  hr_timesheet_type_non_billable/__manifest__.py
  hr_timesheet_type_non_billable/i18n/ca.po
  hr_timesheet_type_non_billable/i18n/es.po
  hr_timesheet_type_non_billable/i18n/hr_timesheet_type_non_billable.pot
  hr_timesheet_type_non_billable/models/__init__.py
  hr_timesheet_type_non_billable/models/account_analytic_line.py
  hr_timesheet_type_non_billable/models/project_project.py
  hr_timesheet_type_non_billable/models/project_task.py
  hr_timesheet_type_non_billable/models/project_time_type.py
  hr_timesheet_type_non_billable/pyproject.toml
  hr_timesheet_type_non_billable/readme/CONTRIBUTORS.md
  hr_timesheet_type_non_billable/readme/DESCRIPTION.md
  hr_timesheet_type_non_billable/readme/USAGE.md
  hr_timesheet_type_non_billable/static/description/icon.png
  hr_timesheet_type_non_billable/static/description/index.html
  hr_timesheet_type_non_billable/tests/__init__.py
  hr_timesheet_type_non_billable/tests/test_hr_timesheet_type_non_billable.py
  hr_timesheet_type_non_billable/views/project_time_type_view.xml
Labels: approved, bot is merging ⏳

#772 [17.0][IMP] hr_timesheet_calendar: create new entries in popup
  hr_timesheet_calendar/README.rst
  hr_timesheet_calendar/__init__.py
  hr_timesheet_calendar/__manifest__.py
  hr_timesheet_calendar/models/__init__.py
  hr_timesheet_calendar/models/account_analytic_line.py
  hr_timesheet_calendar/readme/CONTRIBUTORS.md
  hr_timesheet_calendar/static/description/index.html
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_popover.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_popover.xml
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_renderer.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_controller.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_renderer.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_view.esm.js
  hr_timesheet_calendar/tests/__init__.py
  hr_timesheet_calendar/tests/test_account_analytic_line.py
  hr_timesheet_calendar/views/hr_timesheet_views.xml
Labels: approved, ready to merge, bot is merging ⏳
