Repository OCA/timesheet, pull requests merged in 2025-06, with the labels that each got.

#780 [18.0][MIG] hr_timesheet_calendar: Migration to 18.0
  hr_timesheet_calendar/README.rst
  hr_timesheet_calendar/__init__.py
  hr_timesheet_calendar/__manifest__.py
  hr_timesheet_calendar/i18n/hr_timesheet_calendar.pot
  hr_timesheet_calendar/i18n/it.po
  hr_timesheet_calendar/models/__init__.py
  hr_timesheet_calendar/models/account_analytic_line.py
  hr_timesheet_calendar/models/res_config_settings.py
  hr_timesheet_calendar/pyproject.toml
  hr_timesheet_calendar/readme/CONTRIBUTORS.md
  hr_timesheet_calendar/readme/DESCRIPTION.md
  hr_timesheet_calendar/static/description/icon.png
  hr_timesheet_calendar/static/description/icon.svg
  hr_timesheet_calendar/static/description/index.html
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_popover.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_popover.xml
  hr_timesheet_calendar/static/src/views/timesheet_calendar/common/timesheet_calendar_common_renderer.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_controller.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_renderer.esm.js
  hr_timesheet_calendar/static/src/views/timesheet_calendar/timesheet_calendar_view.esm.js
  hr_timesheet_calendar/tests/__init__.py
  hr_timesheet_calendar/tests/test_account_analytic_line.py
  hr_timesheet_calendar/views/hr_timesheet_views.xml
  hr_timesheet_calendar/views/res_config_settings_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#787 [16.0][IMP] hr_timesheet_type_non_billable: Now working on helpdesk ticket aswell
  hr_timesheet_type_non_billable/README.rst
  hr_timesheet_type_non_billable/__manifest__.py
  hr_timesheet_type_non_billable/models/__init__.py
  hr_timesheet_type_non_billable/models/helpdesk_ticket.py
  hr_timesheet_type_non_billable/tests/test_hr_timesheet_type_non_billable.py
Labels: bot is merging ⏳

#784 [18.0][MIG] hr_timesheet_unusual_days: Migration to 18.0
  hr_timesheet_unusual_days/README.rst
  hr_timesheet_unusual_days/__init__.py
  hr_timesheet_unusual_days/__manifest__.py
  hr_timesheet_unusual_days/i18n/hr_timesheet_unusual_days.pot
  hr_timesheet_unusual_days/i18n/it.po
  hr_timesheet_unusual_days/models/__init__.py
  hr_timesheet_unusual_days/models/account_analytic_line.py
  hr_timesheet_unusual_days/pyproject.toml
  hr_timesheet_unusual_days/readme/CONTRIBUTORS.md
  hr_timesheet_unusual_days/readme/DESCRIPTION.md
  hr_timesheet_unusual_days/static/description/calendar.drawio.png
  hr_timesheet_unusual_days/static/description/icon.png
  hr_timesheet_unusual_days/static/description/index.html
  hr_timesheet_unusual_days/tests/__init__.py
  hr_timesheet_unusual_days/tests/test_account_analytic_line.py
  hr_timesheet_unusual_days/views/hr_timesheet_views.xml
Labels: approved, bot is merging ⏳

#788 [IMP] hr_timesheet_type_non_billable: Now works with helpdesk_ticket aswell
  hr_timesheet_type_non_billable/README.rst
  hr_timesheet_type_non_billable/__manifest__.py
  hr_timesheet_type_non_billable/models/__init__.py
  hr_timesheet_type_non_billable/models/helpdesk_ticket.py
  hr_timesheet_type_non_billable/tests/test_hr_timesheet_type_non_billable.py
Labels: approved, bot is merging ⏳

#790 [17.0][MIG] hr_timesheet_date_order_desc: Migration to 17.0
  hr_timesheet_date_order_desc/README.rst
  hr_timesheet_date_order_desc/__init__.py
  hr_timesheet_date_order_desc/__manifest__.py
  hr_timesheet_date_order_desc/i18n/hr_timesheet_date_order_desc.pot
  hr_timesheet_date_order_desc/i18n/it.po
  hr_timesheet_date_order_desc/pyproject.toml
  hr_timesheet_date_order_desc/readme/CONTRIBUTORS.md
  hr_timesheet_date_order_desc/readme/DESCRIPTION.md
  hr_timesheet_date_order_desc/static/description/icon.png
  hr_timesheet_date_order_desc/static/description/index.html
  hr_timesheet_date_order_desc/views/hr_analytic_timesheet.xml
Labels: approved, ready to merge, bot is merging ⏳

#793 [18.0][MIG] crm_timesheet: Migration to 18.0
  crm_timesheet/README.rst
  crm_timesheet/__init__.py
  crm_timesheet/__manifest__.py
  crm_timesheet/i18n/crm_timesheet.pot
  crm_timesheet/i18n/cs_CZ.po
  crm_timesheet/i18n/de.po
  crm_timesheet/i18n/es.po
  crm_timesheet/i18n/fr.po
  crm_timesheet/i18n/it.po
  crm_timesheet/i18n/nl.po
  crm_timesheet/i18n/pt.po
  crm_timesheet/i18n/pt_BR.po
  crm_timesheet/models/__init__.py
  crm_timesheet/models/account_analytic_line.py
  crm_timesheet/models/crm_lead.py
  crm_timesheet/pyproject.toml
  crm_timesheet/readme/CONTRIBUTORS.md
  crm_timesheet/readme/DESCRIPTION.md
  crm_timesheet/readme/ROADMAP.md
  crm_timesheet/readme/USAGE.md
  crm_timesheet/security/ir.model.access.csv
  crm_timesheet/static/description/icon.png
  crm_timesheet/static/description/index.html
  crm_timesheet/tests/__init__.py
  crm_timesheet/tests/test_account_analytic_line.py
  crm_timesheet/views/crm_lead_view.xml
  crm_timesheet/views/hr_timesheet_view.xml
  crm_timesheet/wizards/__init__.py
  crm_timesheet/wizards/hr_timesheet_switch.py
Labels: approved, ready to merge, bot is merging ⏳
