Repository OCA/timesheet, pull requests merged in 2025-09, with the labels that each got.

#792 [18.0][MIG] hr_timesheet_sheet_autodraft: Migration to 18.0
  hr_timesheet_sheet_autodraft/README.rst
  hr_timesheet_sheet_autodraft/__init__.py
  hr_timesheet_sheet_autodraft/__manifest__.py
  hr_timesheet_sheet_autodraft/i18n/hr_timesheet_sheet_autodraft.pot
  hr_timesheet_sheet_autodraft/i18n/it.po
  hr_timesheet_sheet_autodraft/i18n/nl.po
  hr_timesheet_sheet_autodraft/models/__init__.py
  hr_timesheet_sheet_autodraft/models/account_analytic_line.py
  hr_timesheet_sheet_autodraft/models/res_company.py
  hr_timesheet_sheet_autodraft/models/res_config.py
  hr_timesheet_sheet_autodraft/pyproject.toml
  hr_timesheet_sheet_autodraft/readme/CONFIGURE.md
  hr_timesheet_sheet_autodraft/readme/CONTRIBUTORS.md
  hr_timesheet_sheet_autodraft/readme/DESCRIPTION.md
  hr_timesheet_sheet_autodraft/static/description/icon.png
  hr_timesheet_sheet_autodraft/static/description/index.html
  hr_timesheet_sheet_autodraft/tests/__init__.py
  hr_timesheet_sheet_autodraft/tests/test_hr_timesheet_sheet_autodraft.py
  hr_timesheet_sheet_autodraft/views/account_analytic_line.xml
  hr_timesheet_sheet_autodraft/views/res_config_settings.xml
Labels: approved, bot is merging ⏳

#806 [15.0][MIG] hr_timesheet_portal
  hr_timesheet_portal/README.rst
  hr_timesheet_portal/__init__.py
  hr_timesheet_portal/__manifest__.py
  hr_timesheet_portal/demo/hr_timesheet_portal.xml
  hr_timesheet_portal/i18n/hr_timesheet_portal.pot
  hr_timesheet_portal/i18n/it.po
  hr_timesheet_portal/readme/CONFIGURE.rst
  hr_timesheet_portal/readme/CONTRIBUTORS.rst
  hr_timesheet_portal/readme/DESCRIPTION.rst
  hr_timesheet_portal/security/hr_timesheet_portal_security.xml
  hr_timesheet_portal/security/ir.model.access.csv
  hr_timesheet_portal/static/description/icon.png
  hr_timesheet_portal/static/description/index.html
  hr_timesheet_portal/static/src/css/hr_timesheet_portal.css
  hr_timesheet_portal/static/src/js/hr_timesheet_portal.js
  hr_timesheet_portal/templates/portal.xml
  hr_timesheet_portal/views/hr_employee.xml
  setup/hr_timesheet_portal/odoo/addons/hr_timesheet_portal
  setup/hr_timesheet_portal/setup.py
Labels: bot is merging ⏳

#755 [17.0][ADD] hr_timesheet_autofill_project_off
  hr_timesheet_autofill_project_off/README.rst
  hr_timesheet_autofill_project_off/__init__.py
  hr_timesheet_autofill_project_off/__manifest__.py
  hr_timesheet_autofill_project_off/i18n/hr_timesheet_autofill_project_off.pot
  hr_timesheet_autofill_project_off/models/__init__.py
  hr_timesheet_autofill_project_off/models/hr_timesheet.py
  hr_timesheet_autofill_project_off/pyproject.toml
  hr_timesheet_autofill_project_off/readme/CONTRIBUTORS.md
  hr_timesheet_autofill_project_off/readme/DESCRIPTION.md
  hr_timesheet_autofill_project_off/readme/USAGE.md
  hr_timesheet_autofill_project_off/static/description/icon.png
  hr_timesheet_autofill_project_off/static/description/index.html
  hr_timesheet_autofill_project_off/static/img/01_project_autofill_without_addon.png
  hr_timesheet_autofill_project_off/static/img/02_no_project_autofill_with_addon.png
  hr_timesheet_autofill_project_off/tests/__init__.py
  hr_timesheet_autofill_project_off/tests/test_account_analytic_line_default_get.py
Labels: approved, ready to merge, bot is merging ⏳
